fail_fast: true
repos:
  - repo: local
    hooks:
      
      - id: go-fmt
        name: 🧹 Run go fmt
        entry: bash -c "make check_fmt || (echo '❌ Код автоматически отформатирован! Добавьте изменения (git add) и повторите коммит.' && exit 1)"
        language: system
        pass_filenames: false
        stages: [pre-commit]

      - id: go-mod-tidy
        name: 📦 Check go mod chores
        entry: bash -c "make check_mod || (echo '❌ Файлы go.mod или go.sum изменились! Добавьте их (git add), закоммитьте и повторите пуш.' && exit 1)"
        language: system
        pass_filenames: false
        stages: [manual, pre-push] 

      - id: golangci-lint
        name: 🔍 Run Linter
        entry: make lint
        language: system
        pass_filenames: false
        stages: [pre-push] 

      - id: go-test
        name: 🧪 Run Tests
        entry: make test
        language: system
        pass_filenames: false
        verbose: true
        stages: [pre-push] 

      - id: docker-build
        name: 🐳 Docker Build Check
        entry: make check_building
        language: system
        pass_filenames: false
        stages: [pre-push]
