{
 "title": "App main dashboards",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "PostregSQL metrics",
   "type": "timeseries",
   "description": "Метрики базы данных.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "pg_locks_count{job=\"postgres\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "pg_stat_activity_count{job=\"postgres\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "pg_stat_activity_max_tx_duration{job=\"postgres\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Go metrics for server",
   "type": "timeseries",
   "description": "Метрики аллоцированной памяти, количества горутин и времени работы сборщика мусора на сервере.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "go_memstats_alloc_bytes{instance=\"server:8080\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "go_goroutines{instance=\"server:8080\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "go_gc_duration_seconds{instance=\"server:8080\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP-request metrics",
   "type": "timeseries",
   "description": "Метрики для отслеживания общего количества запросов на сервер и длительности их обработки.",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "http_requests_total{job=\"server\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "http_request_duration_seconds_bucket{job=\"server\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "System metrics",
   "type": "timeseries",
   "description": "Метрики с машины, на которой запущено приложение.",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "node_cpu_seconds_total{mode=\"idle\"}",
     "legendFormat": "__auto"
    },
    { "expr": "node_memory_MemAvailable_bytes", "legendFormat": "__auto" },
    { "expr": "node_filesystem_free_bytes", "legendFormat": "__auto" }
   ]
  }
 ]
}