// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package entities

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson3b07ea0fDecodeBreweryInternalEntities(in *jlexer.Lexer, out *Aggregates) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		in.Skip()
		*out = nil
	} else {
		in.Delim('[')
		if *out == nil {
			if !in.IsDelim(']') {
				*out = make(Aggregates, 0, 0)
			} else {
				*out = Aggregates{}
			}
		} else {
			*out = (*out)[:0]
		}
		for !in.IsDelim(']') {
			var v1 Aggregate
			if in.IsNull() {
				in.Skip()
			} else {
				(v1).UnmarshalEasyJSON(in)
			}
			*out = append(*out, v1)
			in.WantComma()
		}
		in.Delim(']')
	}
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson3b07ea0fEncodeBreweryInternalEntities(out *jwriter.Writer, in Aggregates) {
	if in == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
		out.RawString("null")
	} else {
		out.RawByte('[')
		for v2, v3 := range in {
			if v2 > 0 {
				out.RawByte(',')
			}
			(v3).MarshalEasyJSON(out)
		}
		out.RawByte(']')
	}
}

// MarshalJSON supports json.Marshaler interface
func (v Aggregates) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson3b07ea0fEncodeBreweryInternalEntities(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Aggregates) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson3b07ea0fEncodeBreweryInternalEntities(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Aggregates) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson3b07ea0fDecodeBreweryInternalEntities(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Aggregates) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson3b07ea0fDecodeBreweryInternalEntities(l, v)
}
func easyjson3b07ea0fDecodeBreweryInternalEntities1(in *jlexer.Lexer, out *Aggregate) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ID = uint(in.Uint())
			}
		case "name":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Name = string(in.String())
			}
		case "description":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Description = string(in.String())
			}
		case "numeric_param_ids":
			if in.IsNull() {
				in.Skip()
				out.NumericParameters = nil
			} else {
				in.Delim('[')
				if out.NumericParameters == nil {
					if !in.IsDelim(']') {
						out.NumericParameters = make([]int, 0, 8)
					} else {
						out.NumericParameters = []int{}
					}
				} else {
					out.NumericParameters = (out.NumericParameters)[:0]
				}
				for !in.IsDelim(']') {
					var v4 int
					if in.IsNull() {
						in.Skip()
					} else {
						v4 = int(in.Int())
					}
					out.NumericParameters = append(out.NumericParameters, v4)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "enum_param_ids":
			if in.IsNull() {
				in.Skip()
				out.EnumParameters = nil
			} else {
				in.Delim('[')
				if out.EnumParameters == nil {
					if !in.IsDelim(']') {
						out.EnumParameters = make([]int, 0, 8)
					} else {
						out.EnumParameters = []int{}
					}
				} else {
					out.EnumParameters = (out.EnumParameters)[:0]
				}
				for !in.IsDelim(']') {
					var v5 int
					if in.IsNull() {
						in.Skip()
					} else {
						v5 = int(in.Int())
					}
					out.EnumParameters = append(out.EnumParameters, v5)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson3b07ea0fEncodeBreweryInternalEntities1(out *jwriter.Writer, in Aggregate) {
	out.RawByte('{')
	first := true
	_ = first
	if in.ID != 0 {
		const prefix string = ",\"id\":"
		first = false
		out.RawString(prefix[1:])
		out.Uint(uint(in.ID))
	}
	if in.Name != "" {
		const prefix string = ",\"name\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.Name))
	}
	if in.Description != "" {
		const prefix string = ",\"description\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.Description))
	}
	if len(in.NumericParameters) != 0 {
		const prefix string = ",\"numeric_param_ids\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		{
			out.RawByte('[')
			for v6, v7 := range in.NumericParameters {
				if v6 > 0 {
					out.RawByte(',')
				}
				out.Int(int(v7))
			}
			out.RawByte(']')
		}
	}
	if len(in.EnumParameters) != 0 {
		const prefix string = ",\"enum_param_ids\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		{
			out.RawByte('[')
			for v8, v9 := range in.EnumParameters {
				if v8 > 0 {
					out.RawByte(',')
				}
				out.Int(int(v9))
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Aggregate) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson3b07ea0fEncodeBreweryInternalEntities1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Aggregate) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson3b07ea0fEncodeBreweryInternalEntities1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Aggregate) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson3b07ea0fDecodeBreweryInternalEntities1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Aggregate) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson3b07ea0fDecodeBreweryInternalEntities1(l, v)
}
