// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package entities

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson57ba88e2DecodeBreweryInternalEntities(in *jlexer.Lexer, out *Beers) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		in.Skip()
		*out = nil
	} else {
		in.Delim('[')
		if *out == nil {
			if !in.IsDelim(']') {
				*out = make(Beers, 0, 0)
			} else {
				*out = Beers{}
			}
		} else {
			*out = (*out)[:0]
		}
		for !in.IsDelim(']') {
			var v1 Beer
			if in.IsNull() {
				in.Skip()
			} else {
				(v1).UnmarshalEasyJSON(in)
			}
			*out = append(*out, v1)
			in.WantComma()
		}
		in.Delim(']')
	}
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson57ba88e2EncodeBreweryInternalEntities(out *jwriter.Writer, in Beers) {
	if in == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
		out.RawString("null")
	} else {
		out.RawByte('[')
		for v2, v3 := range in {
			if v2 > 0 {
				out.RawByte(',')
			}
			(v3).MarshalEasyJSON(out)
		}
		out.RawByte(']')
	}
}

// MarshalJSON supports json.Marshaler interface
func (v Beers) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson57ba88e2EncodeBreweryInternalEntities(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Beers) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson57ba88e2EncodeBreweryInternalEntities(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Beers) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson57ba88e2DecodeBreweryInternalEntities(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Beers) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson57ba88e2DecodeBreweryInternalEntities(l, v)
}
func easyjson57ba88e2DecodeBreweryInternalEntities1(in *jlexer.Lexer, out *Beer) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ID = uint(in.Uint())
			}
		case "name":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Name = string(in.String())
			}
		case "rating":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Rating = float32(in.Float32())
			}
		case "description":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Description = string(in.String())
			}
		case "abv":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ABV = float32(in.Float32())
			}
		case "ibu":
			if in.IsNull() {
				in.Skip()
			} else {
				out.IBU = uint8(in.Uint8())
			}
		case "city":
			if in.IsNull() {
				in.Skip()
			} else {
				out.City = string(in.String())
			}
		case "country":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Country = string(in.String())
			}
		case "type":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Type = string(in.String())
			}
		case "category":
			if in.IsNull() {
				in.Skip()
			} else {
				(out.Category).UnmarshalEasyJSON(in)
			}
		case "features":
			if in.IsNull() {
				in.Skip()
				out.Features = nil
			} else {
				in.Delim('[')
				if out.Features == nil {
					if !in.IsDelim(']') {
						out.Features = make([]string, 0, 4)
					} else {
						out.Features = []string{}
					}
				} else {
					out.Features = (out.Features)[:0]
				}
				for !in.IsDelim(']') {
					var v4 string
					if in.IsNull() {
						in.Skip()
					} else {
						v4 = string(in.String())
					}
					out.Features = append(out.Features, v4)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson57ba88e2EncodeBreweryInternalEntities1(out *jwriter.Writer, in Beer) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.Uint(uint(in.ID))
	}
	{
		const prefix string = ",\"name\":"
		out.RawString(prefix)
		out.String(string(in.Name))
	}
	{
		const prefix string = ",\"rating\":"
		out.RawString(prefix)
		out.Float32(float32(in.Rating))
	}
	if in.Description != "" {
		const prefix string = ",\"description\":"
		out.RawString(prefix)
		out.String(string(in.Description))
	}
	{
		const prefix string = ",\"abv\":"
		out.RawString(prefix)
		out.Float32(float32(in.ABV))
	}
	{
		const prefix string = ",\"ibu\":"
		out.RawString(prefix)
		out.Uint8(uint8(in.IBU))
	}
	{
		const prefix string = ",\"city\":"
		out.RawString(prefix)
		out.String(string(in.City))
	}
	{
		const prefix string = ",\"country\":"
		out.RawString(prefix)
		out.String(string(in.Country))
	}
	{
		const prefix string = ",\"type\":"
		out.RawString(prefix)
		out.String(string(in.Type))
	}
	{
		const prefix string = ",\"category\":"
		out.RawString(prefix)
		(in.Category).MarshalEasyJSON(out)
	}
	if len(in.Features) != 0 {
		const prefix string = ",\"features\":"
		out.RawString(prefix)
		{
			out.RawByte('[')
			for v5, v6 := range in.Features {
				if v5 > 0 {
					out.RawByte(',')
				}
				out.String(string(v6))
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Beer) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson57ba88e2EncodeBreweryInternalEntities1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Beer) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson57ba88e2EncodeBreweryInternalEntities1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Beer) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson57ba88e2DecodeBreweryInternalEntities1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Beer) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson57ba88e2DecodeBreweryInternalEntities1(l, v)
}
