// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  entities

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( Beer ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* Beer ) UnmarshalJSON([]byte) error { return nil }
func ( Beer ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* Beer ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_Beer *Beer

func ( Beers ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* Beers ) UnmarshalJSON([]byte) error { return nil }
func ( Beers ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* Beers ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_Beers *Beers
