// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package entities

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson6a91a67cDecodeBreweryInternalEntities(in *jlexer.Lexer, out *ProductCategory) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "category":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ID = int(in.Int())
			}
		case "name":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Name = string(in.String())
			}
		case "level":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Level = int(in.Int())
			}
		case "parent_id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ParentID = int(in.Int())
			}
		case "children_id":
			if in.IsNull() {
				in.Skip()
				out.ChildrenID = nil
			} else {
				in.Delim('[')
				if out.ChildrenID == nil {
					if !in.IsDelim(']') {
						out.ChildrenID = make([]int, 0, 8)
					} else {
						out.ChildrenID = []int{}
					}
				} else {
					out.ChildrenID = (out.ChildrenID)[:0]
				}
				for !in.IsDelim(']') {
					var v1 int
					if in.IsNull() {
						in.Skip()
					} else {
						v1 = int(in.Int())
					}
					out.ChildrenID = append(out.ChildrenID, v1)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6a91a67cEncodeBreweryInternalEntities(out *jwriter.Writer, in ProductCategory) {
	out.RawByte('{')
	first := true
	_ = first
	if in.ID != 0 {
		const prefix string = ",\"category\":"
		first = false
		out.RawString(prefix[1:])
		out.Int(int(in.ID))
	}
	{
		const prefix string = ",\"name\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.Name))
	}
	{
		const prefix string = ",\"level\":"
		out.RawString(prefix)
		out.Int(int(in.Level))
	}
	if in.ParentID != 0 {
		const prefix string = ",\"parent_id\":"
		out.RawString(prefix)
		out.Int(int(in.ParentID))
	}
	if len(in.ChildrenID) != 0 {
		const prefix string = ",\"children_id\":"
		out.RawString(prefix)
		{
			out.RawByte('[')
			for v2, v3 := range in.ChildrenID {
				if v2 > 0 {
					out.RawByte(',')
				}
				out.Int(int(v3))
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v ProductCategory) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6a91a67cEncodeBreweryInternalEntities(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v ProductCategory) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6a91a67cEncodeBreweryInternalEntities(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *ProductCategory) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6a91a67cDecodeBreweryInternalEntities(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *ProductCategory) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6a91a67cDecodeBreweryInternalEntities(l, v)
}
