// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package entities

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson13cd85ffDecodeBreweryInternalEntities(in *jlexer.Lexer, out *NumericParameters) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		in.Skip()
		*out = nil
	} else {
		in.Delim('[')
		if *out == nil {
			if !in.IsDelim(']') {
				*out = make(NumericParameters, 0, 1)
			} else {
				*out = NumericParameters{}
			}
		} else {
			*out = (*out)[:0]
		}
		for !in.IsDelim(']') {
			var v1 NumericParameter
			if in.IsNull() {
				in.Skip()
			} else {
				(v1).UnmarshalEasyJSON(in)
			}
			*out = append(*out, v1)
			in.WantComma()
		}
		in.Delim(']')
	}
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson13cd85ffEncodeBreweryInternalEntities(out *jwriter.Writer, in NumericParameters) {
	if in == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
		out.RawString("null")
	} else {
		out.RawByte('[')
		for v2, v3 := range in {
			if v2 > 0 {
				out.RawByte(',')
			}
			(v3).MarshalEasyJSON(out)
		}
		out.RawByte(']')
	}
}

// MarshalJSON supports json.Marshaler interface
func (v NumericParameters) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson13cd85ffEncodeBreweryInternalEntities(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v NumericParameters) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson13cd85ffEncodeBreweryInternalEntities(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *NumericParameters) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson13cd85ffDecodeBreweryInternalEntities(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *NumericParameters) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson13cd85ffDecodeBreweryInternalEntities(l, v)
}
func easyjson13cd85ffDecodeBreweryInternalEntities1(in *jlexer.Lexer, out *NumericParameter) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ID = uint(in.Uint())
			}
		case "min_val":
			if in.IsNull() {
				in.Skip()
			} else {
				out.MinValue = int(in.Int())
			}
		case "max_val":
			if in.IsNull() {
				in.Skip()
			} else {
				out.MaxValue = int(in.Int())
			}
		case "field_name":
			if in.IsNull() {
				in.Skip()
			} else {
				out.FieldName = string(in.String())
			}
		case "entity_name":
			if in.IsNull() {
				in.Skip()
			} else {
				out.EntityName = string(in.String())
			}
		case "inheritable":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Inheritable = bool(in.Bool())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson13cd85ffEncodeBreweryInternalEntities1(out *jwriter.Writer, in NumericParameter) {
	out.RawByte('{')
	first := true
	_ = first
	if in.ID != 0 {
		const prefix string = ",\"id\":"
		first = false
		out.RawString(prefix[1:])
		out.Uint(uint(in.ID))
	}
	if in.MinValue != 0 {
		const prefix string = ",\"min_val\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Int(int(in.MinValue))
	}
	if in.MaxValue != 0 {
		const prefix string = ",\"max_val\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Int(int(in.MaxValue))
	}
	if in.FieldName != "" {
		const prefix string = ",\"field_name\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.FieldName))
	}
	if in.EntityName != "" {
		const prefix string = ",\"entity_name\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.EntityName))
	}
	if in.Inheritable {
		const prefix string = ",\"inheritable\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Bool(bool(in.Inheritable))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v NumericParameter) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson13cd85ffEncodeBreweryInternalEntities1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v NumericParameter) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson13cd85ffEncodeBreweryInternalEntities1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *NumericParameter) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson13cd85ffDecodeBreweryInternalEntities1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *NumericParameter) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson13cd85ffDecodeBreweryInternalEntities1(l, v)
}
func easyjson13cd85ffDecodeBreweryInternalEntities2(in *jlexer.Lexer, out *EnumParameters) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		in.Skip()
		*out = nil
	} else {
		in.Delim('[')
		if *out == nil {
			if !in.IsDelim(']') {
				*out = make(EnumParameters, 0, 2)
			} else {
				*out = EnumParameters{}
			}
		} else {
			*out = (*out)[:0]
		}
		for !in.IsDelim(']') {
			var v4 EnumParameter
			if in.IsNull() {
				in.Skip()
			} else {
				(v4).UnmarshalEasyJSON(in)
			}
			*out = append(*out, v4)
			in.WantComma()
		}
		in.Delim(']')
	}
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson13cd85ffEncodeBreweryInternalEntities2(out *jwriter.Writer, in EnumParameters) {
	if in == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
		out.RawString("null")
	} else {
		out.RawByte('[')
		for v5, v6 := range in {
			if v5 > 0 {
				out.RawByte(',')
			}
			(v6).MarshalEasyJSON(out)
		}
		out.RawByte(']')
	}
}

// MarshalJSON supports json.Marshaler interface
func (v EnumParameters) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson13cd85ffEncodeBreweryInternalEntities2(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v EnumParameters) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson13cd85ffEncodeBreweryInternalEntities2(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *EnumParameters) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson13cd85ffDecodeBreweryInternalEntities2(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *EnumParameters) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson13cd85ffDecodeBreweryInternalEntities2(l, v)
}
func easyjson13cd85ffDecodeBreweryInternalEntities3(in *jlexer.Lexer, out *EnumParameter) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ID = uint(in.Uint())
			}
		case "enum_class_id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.EnumClassID = uint(in.Uint())
			}
		case "inheritable":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Inheritable = bool(in.Bool())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson13cd85ffEncodeBreweryInternalEntities3(out *jwriter.Writer, in EnumParameter) {
	out.RawByte('{')
	first := true
	_ = first
	if in.ID != 0 {
		const prefix string = ",\"id\":"
		first = false
		out.RawString(prefix[1:])
		out.Uint(uint(in.ID))
	}
	if in.EnumClassID != 0 {
		const prefix string = ",\"enum_class_id\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Uint(uint(in.EnumClassID))
	}
	if in.Inheritable {
		const prefix string = ",\"inheritable\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Bool(bool(in.Inheritable))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v EnumParameter) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson13cd85ffEncodeBreweryInternalEntities3(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v EnumParameter) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson13cd85ffEncodeBreweryInternalEntities3(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *EnumParameter) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson13cd85ffDecodeBreweryInternalEntities3(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *EnumParameter) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson13cd85ffDecodeBreweryInternalEntities3(l, v)
}
