// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  entities

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( Review ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* Review ) UnmarshalJSON([]byte) error { return nil }
func ( Review ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* Review ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_Review *Review

func ( Reviews ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* Reviews ) UnmarshalJSON([]byte) error { return nil }
func ( Reviews ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* Reviews ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_Reviews *Reviews
