definitions:
  entities.Review:
    properties:
      beer_id:
        type: integer
      body:
        type: string
      id:
        type: integer
      rating:
        type: integer
    type: object
  errors.APIError:
    properties:
      error:
        example: VALIDATION_ERROR
        type: string
      message:
        example: Invalid request
        type: string
    type: object
info:
  contact: {}
paths:
  /reviews/{beer_id}:
    post:
      consumes:
      - application/json
      description: create beer's review
      parameters:
      - description: review create by beer id
        in: path
        minimum: 1
        name: beer_id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "201":
          description: Review created
          schema:
            $ref: '#/definitions/entities.Review'
        "400":
          description: failed
          schema:
            $ref: '#/definitions/errors.APIError'
      summary: create beer's review
      tags:
      - Reviews
swagger: "2.0"
