// Code generated by http://github.com/gojuno/minimock (v3.4.7). DO NOT EDIT.

package mocks

//go:generate minimock -i Brewery/internal/usecase.AggregateService -o aggregate_service_mock.go -n AggregateServiceMock -p mocks

import (
	"Brewery/internal/entities"
	"context"
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	"github.com/gojuno/minimock/v3"
)

// AggregateServiceMock implements mm_usecase.AggregateService
type AggregateServiceMock struct {
	t          minimock.Tester
	finishOnce sync.Once

	funcApplyAggregateToCategory          func(ctx context.Context, categoryID uint, aggregateID uint) (i1 int, err error)
	funcApplyAggregateToCategoryOrigin    string
	inspectFuncApplyAggregateToCategory   func(ctx context.Context, categoryID uint, aggregateID uint)
	afterApplyAggregateToCategoryCounter  uint64
	beforeApplyAggregateToCategoryCounter uint64
	ApplyAggregateToCategoryMock          mAggregateServiceMockApplyAggregateToCategory

	funcCreateAggregate          func(ctx context.Context, aggregate *entities.Aggregate) (ap1 *entities.Aggregate, err error)
	funcCreateAggregateOrigin    string
	inspectFuncCreateAggregate   func(ctx context.Context, aggregate *entities.Aggregate)
	afterCreateAggregateCounter  uint64
	beforeCreateAggregateCounter uint64
	CreateAggregateMock          mAggregateServiceMockCreateAggregate

	funcDeleteAggregate          func(ctx context.Context, id uint) (ap1 *entities.Aggregate, err error)
	funcDeleteAggregateOrigin    string
	inspectFuncDeleteAggregate   func(ctx context.Context, id uint)
	afterDeleteAggregateCounter  uint64
	beforeDeleteAggregateCounter uint64
	DeleteAggregateMock          mAggregateServiceMockDeleteAggregate

	funcGetAggregates          func(ctx context.Context, name string) (aa1 []entities.Aggregate, err error)
	funcGetAggregatesOrigin    string
	inspectFuncGetAggregates   func(ctx context.Context, name string)
	afterGetAggregatesCounter  uint64
	beforeGetAggregatesCounter uint64
	GetAggregatesMock          mAggregateServiceMockGetAggregates

	funcUpdateAggregate          func(ctx context.Context, id uint, updates map[string]any) (ap1 *entities.Aggregate, err error)
	funcUpdateAggregateOrigin    string
	inspectFuncUpdateAggregate   func(ctx context.Context, id uint, updates map[string]any)
	afterUpdateAggregateCounter  uint64
	beforeUpdateAggregateCounter uint64
	UpdateAggregateMock          mAggregateServiceMockUpdateAggregate
}

// NewAggregateServiceMock returns a mock for mm_usecase.AggregateService
func NewAggregateServiceMock(t minimock.Tester) *AggregateServiceMock {
	m := &AggregateServiceMock{t: t}

	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.ApplyAggregateToCategoryMock = mAggregateServiceMockApplyAggregateToCategory{mock: m}
	m.ApplyAggregateToCategoryMock.callArgs = []*AggregateServiceMockApplyAggregateToCategoryParams{}

	m.CreateAggregateMock = mAggregateServiceMockCreateAggregate{mock: m}
	m.CreateAggregateMock.callArgs = []*AggregateServiceMockCreateAggregateParams{}

	m.DeleteAggregateMock = mAggregateServiceMockDeleteAggregate{mock: m}
	m.DeleteAggregateMock.callArgs = []*AggregateServiceMockDeleteAggregateParams{}

	m.GetAggregatesMock = mAggregateServiceMockGetAggregates{mock: m}
	m.GetAggregatesMock.callArgs = []*AggregateServiceMockGetAggregatesParams{}

	m.UpdateAggregateMock = mAggregateServiceMockUpdateAggregate{mock: m}
	m.UpdateAggregateMock.callArgs = []*AggregateServiceMockUpdateAggregateParams{}

	t.Cleanup(m.MinimockFinish)

	return m
}

type mAggregateServiceMockApplyAggregateToCategory struct {
	optional           bool
	mock               *AggregateServiceMock
	defaultExpectation *AggregateServiceMockApplyAggregateToCategoryExpectation
	expectations       []*AggregateServiceMockApplyAggregateToCategoryExpectation

	callArgs []*AggregateServiceMockApplyAggregateToCategoryParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// AggregateServiceMockApplyAggregateToCategoryExpectation specifies expectation struct of the AggregateService.ApplyAggregateToCategory
type AggregateServiceMockApplyAggregateToCategoryExpectation struct {
	mock               *AggregateServiceMock
	params             *AggregateServiceMockApplyAggregateToCategoryParams
	paramPtrs          *AggregateServiceMockApplyAggregateToCategoryParamPtrs
	expectationOrigins AggregateServiceMockApplyAggregateToCategoryExpectationOrigins
	results            *AggregateServiceMockApplyAggregateToCategoryResults
	returnOrigin       string
	Counter            uint64
}

// AggregateServiceMockApplyAggregateToCategoryParams contains parameters of the AggregateService.ApplyAggregateToCategory
type AggregateServiceMockApplyAggregateToCategoryParams struct {
	ctx         context.Context
	categoryID  uint
	aggregateID uint
}

// AggregateServiceMockApplyAggregateToCategoryParamPtrs contains pointers to parameters of the AggregateService.ApplyAggregateToCategory
type AggregateServiceMockApplyAggregateToCategoryParamPtrs struct {
	ctx         *context.Context
	categoryID  *uint
	aggregateID *uint
}

// AggregateServiceMockApplyAggregateToCategoryResults contains results of the AggregateService.ApplyAggregateToCategory
type AggregateServiceMockApplyAggregateToCategoryResults struct {
	i1  int
	err error
}

// AggregateServiceMockApplyAggregateToCategoryOrigins contains origins of expectations of the AggregateService.ApplyAggregateToCategory
type AggregateServiceMockApplyAggregateToCategoryExpectationOrigins struct {
	origin            string
	originCtx         string
	originCategoryID  string
	originAggregateID string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmApplyAggregateToCategory *mAggregateServiceMockApplyAggregateToCategory) Optional() *mAggregateServiceMockApplyAggregateToCategory {
	mmApplyAggregateToCategory.optional = true
	return mmApplyAggregateToCategory
}

// Expect sets up expected params for AggregateService.ApplyAggregateToCategory
func (mmApplyAggregateToCategory *mAggregateServiceMockApplyAggregateToCategory) Expect(ctx context.Context, categoryID uint, aggregateID uint) *mAggregateServiceMockApplyAggregateToCategory {
	if mmApplyAggregateToCategory.mock.funcApplyAggregateToCategory != nil {
		mmApplyAggregateToCategory.mock.t.Fatalf("AggregateServiceMock.ApplyAggregateToCategory mock is already set by Set")
	}

	if mmApplyAggregateToCategory.defaultExpectation == nil {
		mmApplyAggregateToCategory.defaultExpectation = &AggregateServiceMockApplyAggregateToCategoryExpectation{}
	}

	if mmApplyAggregateToCategory.defaultExpectation.paramPtrs != nil {
		mmApplyAggregateToCategory.mock.t.Fatalf("AggregateServiceMock.ApplyAggregateToCategory mock is already set by ExpectParams functions")
	}

	mmApplyAggregateToCategory.defaultExpectation.params = &AggregateServiceMockApplyAggregateToCategoryParams{ctx, categoryID, aggregateID}
	mmApplyAggregateToCategory.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmApplyAggregateToCategory.expectations {
		if minimock.Equal(e.params, mmApplyAggregateToCategory.defaultExpectation.params) {
			mmApplyAggregateToCategory.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmApplyAggregateToCategory.defaultExpectation.params)
		}
	}

	return mmApplyAggregateToCategory
}

// ExpectCtxParam1 sets up expected param ctx for AggregateService.ApplyAggregateToCategory
func (mmApplyAggregateToCategory *mAggregateServiceMockApplyAggregateToCategory) ExpectCtxParam1(ctx context.Context) *mAggregateServiceMockApplyAggregateToCategory {
	if mmApplyAggregateToCategory.mock.funcApplyAggregateToCategory != nil {
		mmApplyAggregateToCategory.mock.t.Fatalf("AggregateServiceMock.ApplyAggregateToCategory mock is already set by Set")
	}

	if mmApplyAggregateToCategory.defaultExpectation == nil {
		mmApplyAggregateToCategory.defaultExpectation = &AggregateServiceMockApplyAggregateToCategoryExpectation{}
	}

	if mmApplyAggregateToCategory.defaultExpectation.params != nil {
		mmApplyAggregateToCategory.mock.t.Fatalf("AggregateServiceMock.ApplyAggregateToCategory mock is already set by Expect")
	}

	if mmApplyAggregateToCategory.defaultExpectation.paramPtrs == nil {
		mmApplyAggregateToCategory.defaultExpectation.paramPtrs = &AggregateServiceMockApplyAggregateToCategoryParamPtrs{}
	}
	mmApplyAggregateToCategory.defaultExpectation.paramPtrs.ctx = &ctx
	mmApplyAggregateToCategory.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmApplyAggregateToCategory
}

// ExpectCategoryIDParam2 sets up expected param categoryID for AggregateService.ApplyAggregateToCategory
func (mmApplyAggregateToCategory *mAggregateServiceMockApplyAggregateToCategory) ExpectCategoryIDParam2(categoryID uint) *mAggregateServiceMockApplyAggregateToCategory {
	if mmApplyAggregateToCategory.mock.funcApplyAggregateToCategory != nil {
		mmApplyAggregateToCategory.mock.t.Fatalf("AggregateServiceMock.ApplyAggregateToCategory mock is already set by Set")
	}

	if mmApplyAggregateToCategory.defaultExpectation == nil {
		mmApplyAggregateToCategory.defaultExpectation = &AggregateServiceMockApplyAggregateToCategoryExpectation{}
	}

	if mmApplyAggregateToCategory.defaultExpectation.params != nil {
		mmApplyAggregateToCategory.mock.t.Fatalf("AggregateServiceMock.ApplyAggregateToCategory mock is already set by Expect")
	}

	if mmApplyAggregateToCategory.defaultExpectation.paramPtrs == nil {
		mmApplyAggregateToCategory.defaultExpectation.paramPtrs = &AggregateServiceMockApplyAggregateToCategoryParamPtrs{}
	}
	mmApplyAggregateToCategory.defaultExpectation.paramPtrs.categoryID = &categoryID
	mmApplyAggregateToCategory.defaultExpectation.expectationOrigins.originCategoryID = minimock.CallerInfo(1)

	return mmApplyAggregateToCategory
}

// ExpectAggregateIDParam3 sets up expected param aggregateID for AggregateService.ApplyAggregateToCategory
func (mmApplyAggregateToCategory *mAggregateServiceMockApplyAggregateToCategory) ExpectAggregateIDParam3(aggregateID uint) *mAggregateServiceMockApplyAggregateToCategory {
	if mmApplyAggregateToCategory.mock.funcApplyAggregateToCategory != nil {
		mmApplyAggregateToCategory.mock.t.Fatalf("AggregateServiceMock.ApplyAggregateToCategory mock is already set by Set")
	}

	if mmApplyAggregateToCategory.defaultExpectation == nil {
		mmApplyAggregateToCategory.defaultExpectation = &AggregateServiceMockApplyAggregateToCategoryExpectation{}
	}

	if mmApplyAggregateToCategory.defaultExpectation.params != nil {
		mmApplyAggregateToCategory.mock.t.Fatalf("AggregateServiceMock.ApplyAggregateToCategory mock is already set by Expect")
	}

	if mmApplyAggregateToCategory.defaultExpectation.paramPtrs == nil {
		mmApplyAggregateToCategory.defaultExpectation.paramPtrs = &AggregateServiceMockApplyAggregateToCategoryParamPtrs{}
	}
	mmApplyAggregateToCategory.defaultExpectation.paramPtrs.aggregateID = &aggregateID
	mmApplyAggregateToCategory.defaultExpectation.expectationOrigins.originAggregateID = minimock.CallerInfo(1)

	return mmApplyAggregateToCategory
}

// Inspect accepts an inspector function that has same arguments as the AggregateService.ApplyAggregateToCategory
func (mmApplyAggregateToCategory *mAggregateServiceMockApplyAggregateToCategory) Inspect(f func(ctx context.Context, categoryID uint, aggregateID uint)) *mAggregateServiceMockApplyAggregateToCategory {
	if mmApplyAggregateToCategory.mock.inspectFuncApplyAggregateToCategory != nil {
		mmApplyAggregateToCategory.mock.t.Fatalf("Inspect function is already set for AggregateServiceMock.ApplyAggregateToCategory")
	}

	mmApplyAggregateToCategory.mock.inspectFuncApplyAggregateToCategory = f

	return mmApplyAggregateToCategory
}

// Return sets up results that will be returned by AggregateService.ApplyAggregateToCategory
func (mmApplyAggregateToCategory *mAggregateServiceMockApplyAggregateToCategory) Return(i1 int, err error) *AggregateServiceMock {
	if mmApplyAggregateToCategory.mock.funcApplyAggregateToCategory != nil {
		mmApplyAggregateToCategory.mock.t.Fatalf("AggregateServiceMock.ApplyAggregateToCategory mock is already set by Set")
	}

	if mmApplyAggregateToCategory.defaultExpectation == nil {
		mmApplyAggregateToCategory.defaultExpectation = &AggregateServiceMockApplyAggregateToCategoryExpectation{mock: mmApplyAggregateToCategory.mock}
	}
	mmApplyAggregateToCategory.defaultExpectation.results = &AggregateServiceMockApplyAggregateToCategoryResults{i1, err}
	mmApplyAggregateToCategory.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmApplyAggregateToCategory.mock
}

// Set uses given function f to mock the AggregateService.ApplyAggregateToCategory method
func (mmApplyAggregateToCategory *mAggregateServiceMockApplyAggregateToCategory) Set(f func(ctx context.Context, categoryID uint, aggregateID uint) (i1 int, err error)) *AggregateServiceMock {
	if mmApplyAggregateToCategory.defaultExpectation != nil {
		mmApplyAggregateToCategory.mock.t.Fatalf("Default expectation is already set for the AggregateService.ApplyAggregateToCategory method")
	}

	if len(mmApplyAggregateToCategory.expectations) > 0 {
		mmApplyAggregateToCategory.mock.t.Fatalf("Some expectations are already set for the AggregateService.ApplyAggregateToCategory method")
	}

	mmApplyAggregateToCategory.mock.funcApplyAggregateToCategory = f
	mmApplyAggregateToCategory.mock.funcApplyAggregateToCategoryOrigin = minimock.CallerInfo(1)
	return mmApplyAggregateToCategory.mock
}

// When sets expectation for the AggregateService.ApplyAggregateToCategory which will trigger the result defined by the following
// Then helper
func (mmApplyAggregateToCategory *mAggregateServiceMockApplyAggregateToCategory) When(ctx context.Context, categoryID uint, aggregateID uint) *AggregateServiceMockApplyAggregateToCategoryExpectation {
	if mmApplyAggregateToCategory.mock.funcApplyAggregateToCategory != nil {
		mmApplyAggregateToCategory.mock.t.Fatalf("AggregateServiceMock.ApplyAggregateToCategory mock is already set by Set")
	}

	expectation := &AggregateServiceMockApplyAggregateToCategoryExpectation{
		mock:               mmApplyAggregateToCategory.mock,
		params:             &AggregateServiceMockApplyAggregateToCategoryParams{ctx, categoryID, aggregateID},
		expectationOrigins: AggregateServiceMockApplyAggregateToCategoryExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmApplyAggregateToCategory.expectations = append(mmApplyAggregateToCategory.expectations, expectation)
	return expectation
}

// Then sets up AggregateService.ApplyAggregateToCategory return parameters for the expectation previously defined by the When method
func (e *AggregateServiceMockApplyAggregateToCategoryExpectation) Then(i1 int, err error) *AggregateServiceMock {
	e.results = &AggregateServiceMockApplyAggregateToCategoryResults{i1, err}
	return e.mock
}

// Times sets number of times AggregateService.ApplyAggregateToCategory should be invoked
func (mmApplyAggregateToCategory *mAggregateServiceMockApplyAggregateToCategory) Times(n uint64) *mAggregateServiceMockApplyAggregateToCategory {
	if n == 0 {
		mmApplyAggregateToCategory.mock.t.Fatalf("Times of AggregateServiceMock.ApplyAggregateToCategory mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmApplyAggregateToCategory.expectedInvocations, n)
	mmApplyAggregateToCategory.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmApplyAggregateToCategory
}

func (mmApplyAggregateToCategory *mAggregateServiceMockApplyAggregateToCategory) invocationsDone() bool {
	if len(mmApplyAggregateToCategory.expectations) == 0 && mmApplyAggregateToCategory.defaultExpectation == nil && mmApplyAggregateToCategory.mock.funcApplyAggregateToCategory == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmApplyAggregateToCategory.mock.afterApplyAggregateToCategoryCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmApplyAggregateToCategory.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// ApplyAggregateToCategory implements mm_usecase.AggregateService
func (mmApplyAggregateToCategory *AggregateServiceMock) ApplyAggregateToCategory(ctx context.Context, categoryID uint, aggregateID uint) (i1 int, err error) {
	mm_atomic.AddUint64(&mmApplyAggregateToCategory.beforeApplyAggregateToCategoryCounter, 1)
	defer mm_atomic.AddUint64(&mmApplyAggregateToCategory.afterApplyAggregateToCategoryCounter, 1)

	mmApplyAggregateToCategory.t.Helper()

	if mmApplyAggregateToCategory.inspectFuncApplyAggregateToCategory != nil {
		mmApplyAggregateToCategory.inspectFuncApplyAggregateToCategory(ctx, categoryID, aggregateID)
	}

	mm_params := AggregateServiceMockApplyAggregateToCategoryParams{ctx, categoryID, aggregateID}

	// Record call args
	mmApplyAggregateToCategory.ApplyAggregateToCategoryMock.mutex.Lock()
	mmApplyAggregateToCategory.ApplyAggregateToCategoryMock.callArgs = append(mmApplyAggregateToCategory.ApplyAggregateToCategoryMock.callArgs, &mm_params)
	mmApplyAggregateToCategory.ApplyAggregateToCategoryMock.mutex.Unlock()

	for _, e := range mmApplyAggregateToCategory.ApplyAggregateToCategoryMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.i1, e.results.err
		}
	}

	if mmApplyAggregateToCategory.ApplyAggregateToCategoryMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmApplyAggregateToCategory.ApplyAggregateToCategoryMock.defaultExpectation.Counter, 1)
		mm_want := mmApplyAggregateToCategory.ApplyAggregateToCategoryMock.defaultExpectation.params
		mm_want_ptrs := mmApplyAggregateToCategory.ApplyAggregateToCategoryMock.defaultExpectation.paramPtrs

		mm_got := AggregateServiceMockApplyAggregateToCategoryParams{ctx, categoryID, aggregateID}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmApplyAggregateToCategory.t.Errorf("AggregateServiceMock.ApplyAggregateToCategory got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmApplyAggregateToCategory.ApplyAggregateToCategoryMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.categoryID != nil && !minimock.Equal(*mm_want_ptrs.categoryID, mm_got.categoryID) {
				mmApplyAggregateToCategory.t.Errorf("AggregateServiceMock.ApplyAggregateToCategory got unexpected parameter categoryID, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmApplyAggregateToCategory.ApplyAggregateToCategoryMock.defaultExpectation.expectationOrigins.originCategoryID, *mm_want_ptrs.categoryID, mm_got.categoryID, minimock.Diff(*mm_want_ptrs.categoryID, mm_got.categoryID))
			}

			if mm_want_ptrs.aggregateID != nil && !minimock.Equal(*mm_want_ptrs.aggregateID, mm_got.aggregateID) {
				mmApplyAggregateToCategory.t.Errorf("AggregateServiceMock.ApplyAggregateToCategory got unexpected parameter aggregateID, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmApplyAggregateToCategory.ApplyAggregateToCategoryMock.defaultExpectation.expectationOrigins.originAggregateID, *mm_want_ptrs.aggregateID, mm_got.aggregateID, minimock.Diff(*mm_want_ptrs.aggregateID, mm_got.aggregateID))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmApplyAggregateToCategory.t.Errorf("AggregateServiceMock.ApplyAggregateToCategory got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmApplyAggregateToCategory.ApplyAggregateToCategoryMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmApplyAggregateToCategory.ApplyAggregateToCategoryMock.defaultExpectation.results
		if mm_results == nil {
			mmApplyAggregateToCategory.t.Fatal("No results are set for the AggregateServiceMock.ApplyAggregateToCategory")
		}
		return (*mm_results).i1, (*mm_results).err
	}
	if mmApplyAggregateToCategory.funcApplyAggregateToCategory != nil {
		return mmApplyAggregateToCategory.funcApplyAggregateToCategory(ctx, categoryID, aggregateID)
	}
	mmApplyAggregateToCategory.t.Fatalf("Unexpected call to AggregateServiceMock.ApplyAggregateToCategory. %v %v %v", ctx, categoryID, aggregateID)
	return
}

// ApplyAggregateToCategoryAfterCounter returns a count of finished AggregateServiceMock.ApplyAggregateToCategory invocations
func (mmApplyAggregateToCategory *AggregateServiceMock) ApplyAggregateToCategoryAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmApplyAggregateToCategory.afterApplyAggregateToCategoryCounter)
}

// ApplyAggregateToCategoryBeforeCounter returns a count of AggregateServiceMock.ApplyAggregateToCategory invocations
func (mmApplyAggregateToCategory *AggregateServiceMock) ApplyAggregateToCategoryBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmApplyAggregateToCategory.beforeApplyAggregateToCategoryCounter)
}

// Calls returns a list of arguments used in each call to AggregateServiceMock.ApplyAggregateToCategory.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmApplyAggregateToCategory *mAggregateServiceMockApplyAggregateToCategory) Calls() []*AggregateServiceMockApplyAggregateToCategoryParams {
	mmApplyAggregateToCategory.mutex.RLock()

	argCopy := make([]*AggregateServiceMockApplyAggregateToCategoryParams, len(mmApplyAggregateToCategory.callArgs))
	copy(argCopy, mmApplyAggregateToCategory.callArgs)

	mmApplyAggregateToCategory.mutex.RUnlock()

	return argCopy
}

// MinimockApplyAggregateToCategoryDone returns true if the count of the ApplyAggregateToCategory invocations corresponds
// the number of defined expectations
func (m *AggregateServiceMock) MinimockApplyAggregateToCategoryDone() bool {
	if m.ApplyAggregateToCategoryMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.ApplyAggregateToCategoryMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.ApplyAggregateToCategoryMock.invocationsDone()
}

// MinimockApplyAggregateToCategoryInspect logs each unmet expectation
func (m *AggregateServiceMock) MinimockApplyAggregateToCategoryInspect() {
	for _, e := range m.ApplyAggregateToCategoryMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to AggregateServiceMock.ApplyAggregateToCategory at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterApplyAggregateToCategoryCounter := mm_atomic.LoadUint64(&m.afterApplyAggregateToCategoryCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.ApplyAggregateToCategoryMock.defaultExpectation != nil && afterApplyAggregateToCategoryCounter < 1 {
		if m.ApplyAggregateToCategoryMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to AggregateServiceMock.ApplyAggregateToCategory at\n%s", m.ApplyAggregateToCategoryMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to AggregateServiceMock.ApplyAggregateToCategory at\n%s with params: %#v", m.ApplyAggregateToCategoryMock.defaultExpectation.expectationOrigins.origin, *m.ApplyAggregateToCategoryMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcApplyAggregateToCategory != nil && afterApplyAggregateToCategoryCounter < 1 {
		m.t.Errorf("Expected call to AggregateServiceMock.ApplyAggregateToCategory at\n%s", m.funcApplyAggregateToCategoryOrigin)
	}

	if !m.ApplyAggregateToCategoryMock.invocationsDone() && afterApplyAggregateToCategoryCounter > 0 {
		m.t.Errorf("Expected %d calls to AggregateServiceMock.ApplyAggregateToCategory at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.ApplyAggregateToCategoryMock.expectedInvocations), m.ApplyAggregateToCategoryMock.expectedInvocationsOrigin, afterApplyAggregateToCategoryCounter)
	}
}

type mAggregateServiceMockCreateAggregate struct {
	optional           bool
	mock               *AggregateServiceMock
	defaultExpectation *AggregateServiceMockCreateAggregateExpectation
	expectations       []*AggregateServiceMockCreateAggregateExpectation

	callArgs []*AggregateServiceMockCreateAggregateParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// AggregateServiceMockCreateAggregateExpectation specifies expectation struct of the AggregateService.CreateAggregate
type AggregateServiceMockCreateAggregateExpectation struct {
	mock               *AggregateServiceMock
	params             *AggregateServiceMockCreateAggregateParams
	paramPtrs          *AggregateServiceMockCreateAggregateParamPtrs
	expectationOrigins AggregateServiceMockCreateAggregateExpectationOrigins
	results            *AggregateServiceMockCreateAggregateResults
	returnOrigin       string
	Counter            uint64
}

// AggregateServiceMockCreateAggregateParams contains parameters of the AggregateService.CreateAggregate
type AggregateServiceMockCreateAggregateParams struct {
	ctx       context.Context
	aggregate *entities.Aggregate
}

// AggregateServiceMockCreateAggregateParamPtrs contains pointers to parameters of the AggregateService.CreateAggregate
type AggregateServiceMockCreateAggregateParamPtrs struct {
	ctx       *context.Context
	aggregate **entities.Aggregate
}

// AggregateServiceMockCreateAggregateResults contains results of the AggregateService.CreateAggregate
type AggregateServiceMockCreateAggregateResults struct {
	ap1 *entities.Aggregate
	err error
}

// AggregateServiceMockCreateAggregateOrigins contains origins of expectations of the AggregateService.CreateAggregate
type AggregateServiceMockCreateAggregateExpectationOrigins struct {
	origin          string
	originCtx       string
	originAggregate string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmCreateAggregate *mAggregateServiceMockCreateAggregate) Optional() *mAggregateServiceMockCreateAggregate {
	mmCreateAggregate.optional = true
	return mmCreateAggregate
}

// Expect sets up expected params for AggregateService.CreateAggregate
func (mmCreateAggregate *mAggregateServiceMockCreateAggregate) Expect(ctx context.Context, aggregate *entities.Aggregate) *mAggregateServiceMockCreateAggregate {
	if mmCreateAggregate.mock.funcCreateAggregate != nil {
		mmCreateAggregate.mock.t.Fatalf("AggregateServiceMock.CreateAggregate mock is already set by Set")
	}

	if mmCreateAggregate.defaultExpectation == nil {
		mmCreateAggregate.defaultExpectation = &AggregateServiceMockCreateAggregateExpectation{}
	}

	if mmCreateAggregate.defaultExpectation.paramPtrs != nil {
		mmCreateAggregate.mock.t.Fatalf("AggregateServiceMock.CreateAggregate mock is already set by ExpectParams functions")
	}

	mmCreateAggregate.defaultExpectation.params = &AggregateServiceMockCreateAggregateParams{ctx, aggregate}
	mmCreateAggregate.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmCreateAggregate.expectations {
		if minimock.Equal(e.params, mmCreateAggregate.defaultExpectation.params) {
			mmCreateAggregate.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmCreateAggregate.defaultExpectation.params)
		}
	}

	return mmCreateAggregate
}

// ExpectCtxParam1 sets up expected param ctx for AggregateService.CreateAggregate
func (mmCreateAggregate *mAggregateServiceMockCreateAggregate) ExpectCtxParam1(ctx context.Context) *mAggregateServiceMockCreateAggregate {
	if mmCreateAggregate.mock.funcCreateAggregate != nil {
		mmCreateAggregate.mock.t.Fatalf("AggregateServiceMock.CreateAggregate mock is already set by Set")
	}

	if mmCreateAggregate.defaultExpectation == nil {
		mmCreateAggregate.defaultExpectation = &AggregateServiceMockCreateAggregateExpectation{}
	}

	if mmCreateAggregate.defaultExpectation.params != nil {
		mmCreateAggregate.mock.t.Fatalf("AggregateServiceMock.CreateAggregate mock is already set by Expect")
	}

	if mmCreateAggregate.defaultExpectation.paramPtrs == nil {
		mmCreateAggregate.defaultExpectation.paramPtrs = &AggregateServiceMockCreateAggregateParamPtrs{}
	}
	mmCreateAggregate.defaultExpectation.paramPtrs.ctx = &ctx
	mmCreateAggregate.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmCreateAggregate
}

// ExpectAggregateParam2 sets up expected param aggregate for AggregateService.CreateAggregate
func (mmCreateAggregate *mAggregateServiceMockCreateAggregate) ExpectAggregateParam2(aggregate *entities.Aggregate) *mAggregateServiceMockCreateAggregate {
	if mmCreateAggregate.mock.funcCreateAggregate != nil {
		mmCreateAggregate.mock.t.Fatalf("AggregateServiceMock.CreateAggregate mock is already set by Set")
	}

	if mmCreateAggregate.defaultExpectation == nil {
		mmCreateAggregate.defaultExpectation = &AggregateServiceMockCreateAggregateExpectation{}
	}

	if mmCreateAggregate.defaultExpectation.params != nil {
		mmCreateAggregate.mock.t.Fatalf("AggregateServiceMock.CreateAggregate mock is already set by Expect")
	}

	if mmCreateAggregate.defaultExpectation.paramPtrs == nil {
		mmCreateAggregate.defaultExpectation.paramPtrs = &AggregateServiceMockCreateAggregateParamPtrs{}
	}
	mmCreateAggregate.defaultExpectation.paramPtrs.aggregate = &aggregate
	mmCreateAggregate.defaultExpectation.expectationOrigins.originAggregate = minimock.CallerInfo(1)

	return mmCreateAggregate
}

// Inspect accepts an inspector function that has same arguments as the AggregateService.CreateAggregate
func (mmCreateAggregate *mAggregateServiceMockCreateAggregate) Inspect(f func(ctx context.Context, aggregate *entities.Aggregate)) *mAggregateServiceMockCreateAggregate {
	if mmCreateAggregate.mock.inspectFuncCreateAggregate != nil {
		mmCreateAggregate.mock.t.Fatalf("Inspect function is already set for AggregateServiceMock.CreateAggregate")
	}

	mmCreateAggregate.mock.inspectFuncCreateAggregate = f

	return mmCreateAggregate
}

// Return sets up results that will be returned by AggregateService.CreateAggregate
func (mmCreateAggregate *mAggregateServiceMockCreateAggregate) Return(ap1 *entities.Aggregate, err error) *AggregateServiceMock {
	if mmCreateAggregate.mock.funcCreateAggregate != nil {
		mmCreateAggregate.mock.t.Fatalf("AggregateServiceMock.CreateAggregate mock is already set by Set")
	}

	if mmCreateAggregate.defaultExpectation == nil {
		mmCreateAggregate.defaultExpectation = &AggregateServiceMockCreateAggregateExpectation{mock: mmCreateAggregate.mock}
	}
	mmCreateAggregate.defaultExpectation.results = &AggregateServiceMockCreateAggregateResults{ap1, err}
	mmCreateAggregate.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmCreateAggregate.mock
}

// Set uses given function f to mock the AggregateService.CreateAggregate method
func (mmCreateAggregate *mAggregateServiceMockCreateAggregate) Set(f func(ctx context.Context, aggregate *entities.Aggregate) (ap1 *entities.Aggregate, err error)) *AggregateServiceMock {
	if mmCreateAggregate.defaultExpectation != nil {
		mmCreateAggregate.mock.t.Fatalf("Default expectation is already set for the AggregateService.CreateAggregate method")
	}

	if len(mmCreateAggregate.expectations) > 0 {
		mmCreateAggregate.mock.t.Fatalf("Some expectations are already set for the AggregateService.CreateAggregate method")
	}

	mmCreateAggregate.mock.funcCreateAggregate = f
	mmCreateAggregate.mock.funcCreateAggregateOrigin = minimock.CallerInfo(1)
	return mmCreateAggregate.mock
}

// When sets expectation for the AggregateService.CreateAggregate which will trigger the result defined by the following
// Then helper
func (mmCreateAggregate *mAggregateServiceMockCreateAggregate) When(ctx context.Context, aggregate *entities.Aggregate) *AggregateServiceMockCreateAggregateExpectation {
	if mmCreateAggregate.mock.funcCreateAggregate != nil {
		mmCreateAggregate.mock.t.Fatalf("AggregateServiceMock.CreateAggregate mock is already set by Set")
	}

	expectation := &AggregateServiceMockCreateAggregateExpectation{
		mock:               mmCreateAggregate.mock,
		params:             &AggregateServiceMockCreateAggregateParams{ctx, aggregate},
		expectationOrigins: AggregateServiceMockCreateAggregateExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmCreateAggregate.expectations = append(mmCreateAggregate.expectations, expectation)
	return expectation
}

// Then sets up AggregateService.CreateAggregate return parameters for the expectation previously defined by the When method
func (e *AggregateServiceMockCreateAggregateExpectation) Then(ap1 *entities.Aggregate, err error) *AggregateServiceMock {
	e.results = &AggregateServiceMockCreateAggregateResults{ap1, err}
	return e.mock
}

// Times sets number of times AggregateService.CreateAggregate should be invoked
func (mmCreateAggregate *mAggregateServiceMockCreateAggregate) Times(n uint64) *mAggregateServiceMockCreateAggregate {
	if n == 0 {
		mmCreateAggregate.mock.t.Fatalf("Times of AggregateServiceMock.CreateAggregate mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmCreateAggregate.expectedInvocations, n)
	mmCreateAggregate.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmCreateAggregate
}

func (mmCreateAggregate *mAggregateServiceMockCreateAggregate) invocationsDone() bool {
	if len(mmCreateAggregate.expectations) == 0 && mmCreateAggregate.defaultExpectation == nil && mmCreateAggregate.mock.funcCreateAggregate == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmCreateAggregate.mock.afterCreateAggregateCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmCreateAggregate.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// CreateAggregate implements mm_usecase.AggregateService
func (mmCreateAggregate *AggregateServiceMock) CreateAggregate(ctx context.Context, aggregate *entities.Aggregate) (ap1 *entities.Aggregate, err error) {
	mm_atomic.AddUint64(&mmCreateAggregate.beforeCreateAggregateCounter, 1)
	defer mm_atomic.AddUint64(&mmCreateAggregate.afterCreateAggregateCounter, 1)

	mmCreateAggregate.t.Helper()

	if mmCreateAggregate.inspectFuncCreateAggregate != nil {
		mmCreateAggregate.inspectFuncCreateAggregate(ctx, aggregate)
	}

	mm_params := AggregateServiceMockCreateAggregateParams{ctx, aggregate}

	// Record call args
	mmCreateAggregate.CreateAggregateMock.mutex.Lock()
	mmCreateAggregate.CreateAggregateMock.callArgs = append(mmCreateAggregate.CreateAggregateMock.callArgs, &mm_params)
	mmCreateAggregate.CreateAggregateMock.mutex.Unlock()

	for _, e := range mmCreateAggregate.CreateAggregateMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.ap1, e.results.err
		}
	}

	if mmCreateAggregate.CreateAggregateMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmCreateAggregate.CreateAggregateMock.defaultExpectation.Counter, 1)
		mm_want := mmCreateAggregate.CreateAggregateMock.defaultExpectation.params
		mm_want_ptrs := mmCreateAggregate.CreateAggregateMock.defaultExpectation.paramPtrs

		mm_got := AggregateServiceMockCreateAggregateParams{ctx, aggregate}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmCreateAggregate.t.Errorf("AggregateServiceMock.CreateAggregate got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmCreateAggregate.CreateAggregateMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.aggregate != nil && !minimock.Equal(*mm_want_ptrs.aggregate, mm_got.aggregate) {
				mmCreateAggregate.t.Errorf("AggregateServiceMock.CreateAggregate got unexpected parameter aggregate, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmCreateAggregate.CreateAggregateMock.defaultExpectation.expectationOrigins.originAggregate, *mm_want_ptrs.aggregate, mm_got.aggregate, minimock.Diff(*mm_want_ptrs.aggregate, mm_got.aggregate))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmCreateAggregate.t.Errorf("AggregateServiceMock.CreateAggregate got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmCreateAggregate.CreateAggregateMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmCreateAggregate.CreateAggregateMock.defaultExpectation.results
		if mm_results == nil {
			mmCreateAggregate.t.Fatal("No results are set for the AggregateServiceMock.CreateAggregate")
		}
		return (*mm_results).ap1, (*mm_results).err
	}
	if mmCreateAggregate.funcCreateAggregate != nil {
		return mmCreateAggregate.funcCreateAggregate(ctx, aggregate)
	}
	mmCreateAggregate.t.Fatalf("Unexpected call to AggregateServiceMock.CreateAggregate. %v %v", ctx, aggregate)
	return
}

// CreateAggregateAfterCounter returns a count of finished AggregateServiceMock.CreateAggregate invocations
func (mmCreateAggregate *AggregateServiceMock) CreateAggregateAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmCreateAggregate.afterCreateAggregateCounter)
}

// CreateAggregateBeforeCounter returns a count of AggregateServiceMock.CreateAggregate invocations
func (mmCreateAggregate *AggregateServiceMock) CreateAggregateBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmCreateAggregate.beforeCreateAggregateCounter)
}

// Calls returns a list of arguments used in each call to AggregateServiceMock.CreateAggregate.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmCreateAggregate *mAggregateServiceMockCreateAggregate) Calls() []*AggregateServiceMockCreateAggregateParams {
	mmCreateAggregate.mutex.RLock()

	argCopy := make([]*AggregateServiceMockCreateAggregateParams, len(mmCreateAggregate.callArgs))
	copy(argCopy, mmCreateAggregate.callArgs)

	mmCreateAggregate.mutex.RUnlock()

	return argCopy
}

// MinimockCreateAggregateDone returns true if the count of the CreateAggregate invocations corresponds
// the number of defined expectations
func (m *AggregateServiceMock) MinimockCreateAggregateDone() bool {
	if m.CreateAggregateMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.CreateAggregateMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.CreateAggregateMock.invocationsDone()
}

// MinimockCreateAggregateInspect logs each unmet expectation
func (m *AggregateServiceMock) MinimockCreateAggregateInspect() {
	for _, e := range m.CreateAggregateMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to AggregateServiceMock.CreateAggregate at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterCreateAggregateCounter := mm_atomic.LoadUint64(&m.afterCreateAggregateCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.CreateAggregateMock.defaultExpectation != nil && afterCreateAggregateCounter < 1 {
		if m.CreateAggregateMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to AggregateServiceMock.CreateAggregate at\n%s", m.CreateAggregateMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to AggregateServiceMock.CreateAggregate at\n%s with params: %#v", m.CreateAggregateMock.defaultExpectation.expectationOrigins.origin, *m.CreateAggregateMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcCreateAggregate != nil && afterCreateAggregateCounter < 1 {
		m.t.Errorf("Expected call to AggregateServiceMock.CreateAggregate at\n%s", m.funcCreateAggregateOrigin)
	}

	if !m.CreateAggregateMock.invocationsDone() && afterCreateAggregateCounter > 0 {
		m.t.Errorf("Expected %d calls to AggregateServiceMock.CreateAggregate at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.CreateAggregateMock.expectedInvocations), m.CreateAggregateMock.expectedInvocationsOrigin, afterCreateAggregateCounter)
	}
}

type mAggregateServiceMockDeleteAggregate struct {
	optional           bool
	mock               *AggregateServiceMock
	defaultExpectation *AggregateServiceMockDeleteAggregateExpectation
	expectations       []*AggregateServiceMockDeleteAggregateExpectation

	callArgs []*AggregateServiceMockDeleteAggregateParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// AggregateServiceMockDeleteAggregateExpectation specifies expectation struct of the AggregateService.DeleteAggregate
type AggregateServiceMockDeleteAggregateExpectation struct {
	mock               *AggregateServiceMock
	params             *AggregateServiceMockDeleteAggregateParams
	paramPtrs          *AggregateServiceMockDeleteAggregateParamPtrs
	expectationOrigins AggregateServiceMockDeleteAggregateExpectationOrigins
	results            *AggregateServiceMockDeleteAggregateResults
	returnOrigin       string
	Counter            uint64
}

// AggregateServiceMockDeleteAggregateParams contains parameters of the AggregateService.DeleteAggregate
type AggregateServiceMockDeleteAggregateParams struct {
	ctx context.Context
	id  uint
}

// AggregateServiceMockDeleteAggregateParamPtrs contains pointers to parameters of the AggregateService.DeleteAggregate
type AggregateServiceMockDeleteAggregateParamPtrs struct {
	ctx *context.Context
	id  *uint
}

// AggregateServiceMockDeleteAggregateResults contains results of the AggregateService.DeleteAggregate
type AggregateServiceMockDeleteAggregateResults struct {
	ap1 *entities.Aggregate
	err error
}

// AggregateServiceMockDeleteAggregateOrigins contains origins of expectations of the AggregateService.DeleteAggregate
type AggregateServiceMockDeleteAggregateExpectationOrigins struct {
	origin    string
	originCtx string
	originId  string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmDeleteAggregate *mAggregateServiceMockDeleteAggregate) Optional() *mAggregateServiceMockDeleteAggregate {
	mmDeleteAggregate.optional = true
	return mmDeleteAggregate
}

// Expect sets up expected params for AggregateService.DeleteAggregate
func (mmDeleteAggregate *mAggregateServiceMockDeleteAggregate) Expect(ctx context.Context, id uint) *mAggregateServiceMockDeleteAggregate {
	if mmDeleteAggregate.mock.funcDeleteAggregate != nil {
		mmDeleteAggregate.mock.t.Fatalf("AggregateServiceMock.DeleteAggregate mock is already set by Set")
	}

	if mmDeleteAggregate.defaultExpectation == nil {
		mmDeleteAggregate.defaultExpectation = &AggregateServiceMockDeleteAggregateExpectation{}
	}

	if mmDeleteAggregate.defaultExpectation.paramPtrs != nil {
		mmDeleteAggregate.mock.t.Fatalf("AggregateServiceMock.DeleteAggregate mock is already set by ExpectParams functions")
	}

	mmDeleteAggregate.defaultExpectation.params = &AggregateServiceMockDeleteAggregateParams{ctx, id}
	mmDeleteAggregate.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmDeleteAggregate.expectations {
		if minimock.Equal(e.params, mmDeleteAggregate.defaultExpectation.params) {
			mmDeleteAggregate.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmDeleteAggregate.defaultExpectation.params)
		}
	}

	return mmDeleteAggregate
}

// ExpectCtxParam1 sets up expected param ctx for AggregateService.DeleteAggregate
func (mmDeleteAggregate *mAggregateServiceMockDeleteAggregate) ExpectCtxParam1(ctx context.Context) *mAggregateServiceMockDeleteAggregate {
	if mmDeleteAggregate.mock.funcDeleteAggregate != nil {
		mmDeleteAggregate.mock.t.Fatalf("AggregateServiceMock.DeleteAggregate mock is already set by Set")
	}

	if mmDeleteAggregate.defaultExpectation == nil {
		mmDeleteAggregate.defaultExpectation = &AggregateServiceMockDeleteAggregateExpectation{}
	}

	if mmDeleteAggregate.defaultExpectation.params != nil {
		mmDeleteAggregate.mock.t.Fatalf("AggregateServiceMock.DeleteAggregate mock is already set by Expect")
	}

	if mmDeleteAggregate.defaultExpectation.paramPtrs == nil {
		mmDeleteAggregate.defaultExpectation.paramPtrs = &AggregateServiceMockDeleteAggregateParamPtrs{}
	}
	mmDeleteAggregate.defaultExpectation.paramPtrs.ctx = &ctx
	mmDeleteAggregate.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmDeleteAggregate
}

// ExpectIdParam2 sets up expected param id for AggregateService.DeleteAggregate
func (mmDeleteAggregate *mAggregateServiceMockDeleteAggregate) ExpectIdParam2(id uint) *mAggregateServiceMockDeleteAggregate {
	if mmDeleteAggregate.mock.funcDeleteAggregate != nil {
		mmDeleteAggregate.mock.t.Fatalf("AggregateServiceMock.DeleteAggregate mock is already set by Set")
	}

	if mmDeleteAggregate.defaultExpectation == nil {
		mmDeleteAggregate.defaultExpectation = &AggregateServiceMockDeleteAggregateExpectation{}
	}

	if mmDeleteAggregate.defaultExpectation.params != nil {
		mmDeleteAggregate.mock.t.Fatalf("AggregateServiceMock.DeleteAggregate mock is already set by Expect")
	}

	if mmDeleteAggregate.defaultExpectation.paramPtrs == nil {
		mmDeleteAggregate.defaultExpectation.paramPtrs = &AggregateServiceMockDeleteAggregateParamPtrs{}
	}
	mmDeleteAggregate.defaultExpectation.paramPtrs.id = &id
	mmDeleteAggregate.defaultExpectation.expectationOrigins.originId = minimock.CallerInfo(1)

	return mmDeleteAggregate
}

// Inspect accepts an inspector function that has same arguments as the AggregateService.DeleteAggregate
func (mmDeleteAggregate *mAggregateServiceMockDeleteAggregate) Inspect(f func(ctx context.Context, id uint)) *mAggregateServiceMockDeleteAggregate {
	if mmDeleteAggregate.mock.inspectFuncDeleteAggregate != nil {
		mmDeleteAggregate.mock.t.Fatalf("Inspect function is already set for AggregateServiceMock.DeleteAggregate")
	}

	mmDeleteAggregate.mock.inspectFuncDeleteAggregate = f

	return mmDeleteAggregate
}

// Return sets up results that will be returned by AggregateService.DeleteAggregate
func (mmDeleteAggregate *mAggregateServiceMockDeleteAggregate) Return(ap1 *entities.Aggregate, err error) *AggregateServiceMock {
	if mmDeleteAggregate.mock.funcDeleteAggregate != nil {
		mmDeleteAggregate.mock.t.Fatalf("AggregateServiceMock.DeleteAggregate mock is already set by Set")
	}

	if mmDeleteAggregate.defaultExpectation == nil {
		mmDeleteAggregate.defaultExpectation = &AggregateServiceMockDeleteAggregateExpectation{mock: mmDeleteAggregate.mock}
	}
	mmDeleteAggregate.defaultExpectation.results = &AggregateServiceMockDeleteAggregateResults{ap1, err}
	mmDeleteAggregate.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmDeleteAggregate.mock
}

// Set uses given function f to mock the AggregateService.DeleteAggregate method
func (mmDeleteAggregate *mAggregateServiceMockDeleteAggregate) Set(f func(ctx context.Context, id uint) (ap1 *entities.Aggregate, err error)) *AggregateServiceMock {
	if mmDeleteAggregate.defaultExpectation != nil {
		mmDeleteAggregate.mock.t.Fatalf("Default expectation is already set for the AggregateService.DeleteAggregate method")
	}

	if len(mmDeleteAggregate.expectations) > 0 {
		mmDeleteAggregate.mock.t.Fatalf("Some expectations are already set for the AggregateService.DeleteAggregate method")
	}

	mmDeleteAggregate.mock.funcDeleteAggregate = f
	mmDeleteAggregate.mock.funcDeleteAggregateOrigin = minimock.CallerInfo(1)
	return mmDeleteAggregate.mock
}

// When sets expectation for the AggregateService.DeleteAggregate which will trigger the result defined by the following
// Then helper
func (mmDeleteAggregate *mAggregateServiceMockDeleteAggregate) When(ctx context.Context, id uint) *AggregateServiceMockDeleteAggregateExpectation {
	if mmDeleteAggregate.mock.funcDeleteAggregate != nil {
		mmDeleteAggregate.mock.t.Fatalf("AggregateServiceMock.DeleteAggregate mock is already set by Set")
	}

	expectation := &AggregateServiceMockDeleteAggregateExpectation{
		mock:               mmDeleteAggregate.mock,
		params:             &AggregateServiceMockDeleteAggregateParams{ctx, id},
		expectationOrigins: AggregateServiceMockDeleteAggregateExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmDeleteAggregate.expectations = append(mmDeleteAggregate.expectations, expectation)
	return expectation
}

// Then sets up AggregateService.DeleteAggregate return parameters for the expectation previously defined by the When method
func (e *AggregateServiceMockDeleteAggregateExpectation) Then(ap1 *entities.Aggregate, err error) *AggregateServiceMock {
	e.results = &AggregateServiceMockDeleteAggregateResults{ap1, err}
	return e.mock
}

// Times sets number of times AggregateService.DeleteAggregate should be invoked
func (mmDeleteAggregate *mAggregateServiceMockDeleteAggregate) Times(n uint64) *mAggregateServiceMockDeleteAggregate {
	if n == 0 {
		mmDeleteAggregate.mock.t.Fatalf("Times of AggregateServiceMock.DeleteAggregate mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmDeleteAggregate.expectedInvocations, n)
	mmDeleteAggregate.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmDeleteAggregate
}

func (mmDeleteAggregate *mAggregateServiceMockDeleteAggregate) invocationsDone() bool {
	if len(mmDeleteAggregate.expectations) == 0 && mmDeleteAggregate.defaultExpectation == nil && mmDeleteAggregate.mock.funcDeleteAggregate == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmDeleteAggregate.mock.afterDeleteAggregateCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmDeleteAggregate.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// DeleteAggregate implements mm_usecase.AggregateService
func (mmDeleteAggregate *AggregateServiceMock) DeleteAggregate(ctx context.Context, id uint) (ap1 *entities.Aggregate, err error) {
	mm_atomic.AddUint64(&mmDeleteAggregate.beforeDeleteAggregateCounter, 1)
	defer mm_atomic.AddUint64(&mmDeleteAggregate.afterDeleteAggregateCounter, 1)

	mmDeleteAggregate.t.Helper()

	if mmDeleteAggregate.inspectFuncDeleteAggregate != nil {
		mmDeleteAggregate.inspectFuncDeleteAggregate(ctx, id)
	}

	mm_params := AggregateServiceMockDeleteAggregateParams{ctx, id}

	// Record call args
	mmDeleteAggregate.DeleteAggregateMock.mutex.Lock()
	mmDeleteAggregate.DeleteAggregateMock.callArgs = append(mmDeleteAggregate.DeleteAggregateMock.callArgs, &mm_params)
	mmDeleteAggregate.DeleteAggregateMock.mutex.Unlock()

	for _, e := range mmDeleteAggregate.DeleteAggregateMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.ap1, e.results.err
		}
	}

	if mmDeleteAggregate.DeleteAggregateMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmDeleteAggregate.DeleteAggregateMock.defaultExpectation.Counter, 1)
		mm_want := mmDeleteAggregate.DeleteAggregateMock.defaultExpectation.params
		mm_want_ptrs := mmDeleteAggregate.DeleteAggregateMock.defaultExpectation.paramPtrs

		mm_got := AggregateServiceMockDeleteAggregateParams{ctx, id}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmDeleteAggregate.t.Errorf("AggregateServiceMock.DeleteAggregate got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmDeleteAggregate.DeleteAggregateMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.id != nil && !minimock.Equal(*mm_want_ptrs.id, mm_got.id) {
				mmDeleteAggregate.t.Errorf("AggregateServiceMock.DeleteAggregate got unexpected parameter id, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmDeleteAggregate.DeleteAggregateMock.defaultExpectation.expectationOrigins.originId, *mm_want_ptrs.id, mm_got.id, minimock.Diff(*mm_want_ptrs.id, mm_got.id))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmDeleteAggregate.t.Errorf("AggregateServiceMock.DeleteAggregate got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmDeleteAggregate.DeleteAggregateMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmDeleteAggregate.DeleteAggregateMock.defaultExpectation.results
		if mm_results == nil {
			mmDeleteAggregate.t.Fatal("No results are set for the AggregateServiceMock.DeleteAggregate")
		}
		return (*mm_results).ap1, (*mm_results).err
	}
	if mmDeleteAggregate.funcDeleteAggregate != nil {
		return mmDeleteAggregate.funcDeleteAggregate(ctx, id)
	}
	mmDeleteAggregate.t.Fatalf("Unexpected call to AggregateServiceMock.DeleteAggregate. %v %v", ctx, id)
	return
}

// DeleteAggregateAfterCounter returns a count of finished AggregateServiceMock.DeleteAggregate invocations
func (mmDeleteAggregate *AggregateServiceMock) DeleteAggregateAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmDeleteAggregate.afterDeleteAggregateCounter)
}

// DeleteAggregateBeforeCounter returns a count of AggregateServiceMock.DeleteAggregate invocations
func (mmDeleteAggregate *AggregateServiceMock) DeleteAggregateBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmDeleteAggregate.beforeDeleteAggregateCounter)
}

// Calls returns a list of arguments used in each call to AggregateServiceMock.DeleteAggregate.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmDeleteAggregate *mAggregateServiceMockDeleteAggregate) Calls() []*AggregateServiceMockDeleteAggregateParams {
	mmDeleteAggregate.mutex.RLock()

	argCopy := make([]*AggregateServiceMockDeleteAggregateParams, len(mmDeleteAggregate.callArgs))
	copy(argCopy, mmDeleteAggregate.callArgs)

	mmDeleteAggregate.mutex.RUnlock()

	return argCopy
}

// MinimockDeleteAggregateDone returns true if the count of the DeleteAggregate invocations corresponds
// the number of defined expectations
func (m *AggregateServiceMock) MinimockDeleteAggregateDone() bool {
	if m.DeleteAggregateMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.DeleteAggregateMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.DeleteAggregateMock.invocationsDone()
}

// MinimockDeleteAggregateInspect logs each unmet expectation
func (m *AggregateServiceMock) MinimockDeleteAggregateInspect() {
	for _, e := range m.DeleteAggregateMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to AggregateServiceMock.DeleteAggregate at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterDeleteAggregateCounter := mm_atomic.LoadUint64(&m.afterDeleteAggregateCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.DeleteAggregateMock.defaultExpectation != nil && afterDeleteAggregateCounter < 1 {
		if m.DeleteAggregateMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to AggregateServiceMock.DeleteAggregate at\n%s", m.DeleteAggregateMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to AggregateServiceMock.DeleteAggregate at\n%s with params: %#v", m.DeleteAggregateMock.defaultExpectation.expectationOrigins.origin, *m.DeleteAggregateMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcDeleteAggregate != nil && afterDeleteAggregateCounter < 1 {
		m.t.Errorf("Expected call to AggregateServiceMock.DeleteAggregate at\n%s", m.funcDeleteAggregateOrigin)
	}

	if !m.DeleteAggregateMock.invocationsDone() && afterDeleteAggregateCounter > 0 {
		m.t.Errorf("Expected %d calls to AggregateServiceMock.DeleteAggregate at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.DeleteAggregateMock.expectedInvocations), m.DeleteAggregateMock.expectedInvocationsOrigin, afterDeleteAggregateCounter)
	}
}

type mAggregateServiceMockGetAggregates struct {
	optional           bool
	mock               *AggregateServiceMock
	defaultExpectation *AggregateServiceMockGetAggregatesExpectation
	expectations       []*AggregateServiceMockGetAggregatesExpectation

	callArgs []*AggregateServiceMockGetAggregatesParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// AggregateServiceMockGetAggregatesExpectation specifies expectation struct of the AggregateService.GetAggregates
type AggregateServiceMockGetAggregatesExpectation struct {
	mock               *AggregateServiceMock
	params             *AggregateServiceMockGetAggregatesParams
	paramPtrs          *AggregateServiceMockGetAggregatesParamPtrs
	expectationOrigins AggregateServiceMockGetAggregatesExpectationOrigins
	results            *AggregateServiceMockGetAggregatesResults
	returnOrigin       string
	Counter            uint64
}

// AggregateServiceMockGetAggregatesParams contains parameters of the AggregateService.GetAggregates
type AggregateServiceMockGetAggregatesParams struct {
	ctx  context.Context
	name string
}

// AggregateServiceMockGetAggregatesParamPtrs contains pointers to parameters of the AggregateService.GetAggregates
type AggregateServiceMockGetAggregatesParamPtrs struct {
	ctx  *context.Context
	name *string
}

// AggregateServiceMockGetAggregatesResults contains results of the AggregateService.GetAggregates
type AggregateServiceMockGetAggregatesResults struct {
	aa1 []entities.Aggregate
	err error
}

// AggregateServiceMockGetAggregatesOrigins contains origins of expectations of the AggregateService.GetAggregates
type AggregateServiceMockGetAggregatesExpectationOrigins struct {
	origin     string
	originCtx  string
	originName string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmGetAggregates *mAggregateServiceMockGetAggregates) Optional() *mAggregateServiceMockGetAggregates {
	mmGetAggregates.optional = true
	return mmGetAggregates
}

// Expect sets up expected params for AggregateService.GetAggregates
func (mmGetAggregates *mAggregateServiceMockGetAggregates) Expect(ctx context.Context, name string) *mAggregateServiceMockGetAggregates {
	if mmGetAggregates.mock.funcGetAggregates != nil {
		mmGetAggregates.mock.t.Fatalf("AggregateServiceMock.GetAggregates mock is already set by Set")
	}

	if mmGetAggregates.defaultExpectation == nil {
		mmGetAggregates.defaultExpectation = &AggregateServiceMockGetAggregatesExpectation{}
	}

	if mmGetAggregates.defaultExpectation.paramPtrs != nil {
		mmGetAggregates.mock.t.Fatalf("AggregateServiceMock.GetAggregates mock is already set by ExpectParams functions")
	}

	mmGetAggregates.defaultExpectation.params = &AggregateServiceMockGetAggregatesParams{ctx, name}
	mmGetAggregates.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmGetAggregates.expectations {
		if minimock.Equal(e.params, mmGetAggregates.defaultExpectation.params) {
			mmGetAggregates.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmGetAggregates.defaultExpectation.params)
		}
	}

	return mmGetAggregates
}

// ExpectCtxParam1 sets up expected param ctx for AggregateService.GetAggregates
func (mmGetAggregates *mAggregateServiceMockGetAggregates) ExpectCtxParam1(ctx context.Context) *mAggregateServiceMockGetAggregates {
	if mmGetAggregates.mock.funcGetAggregates != nil {
		mmGetAggregates.mock.t.Fatalf("AggregateServiceMock.GetAggregates mock is already set by Set")
	}

	if mmGetAggregates.defaultExpectation == nil {
		mmGetAggregates.defaultExpectation = &AggregateServiceMockGetAggregatesExpectation{}
	}

	if mmGetAggregates.defaultExpectation.params != nil {
		mmGetAggregates.mock.t.Fatalf("AggregateServiceMock.GetAggregates mock is already set by Expect")
	}

	if mmGetAggregates.defaultExpectation.paramPtrs == nil {
		mmGetAggregates.defaultExpectation.paramPtrs = &AggregateServiceMockGetAggregatesParamPtrs{}
	}
	mmGetAggregates.defaultExpectation.paramPtrs.ctx = &ctx
	mmGetAggregates.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmGetAggregates
}

// ExpectNameParam2 sets up expected param name for AggregateService.GetAggregates
func (mmGetAggregates *mAggregateServiceMockGetAggregates) ExpectNameParam2(name string) *mAggregateServiceMockGetAggregates {
	if mmGetAggregates.mock.funcGetAggregates != nil {
		mmGetAggregates.mock.t.Fatalf("AggregateServiceMock.GetAggregates mock is already set by Set")
	}

	if mmGetAggregates.defaultExpectation == nil {
		mmGetAggregates.defaultExpectation = &AggregateServiceMockGetAggregatesExpectation{}
	}

	if mmGetAggregates.defaultExpectation.params != nil {
		mmGetAggregates.mock.t.Fatalf("AggregateServiceMock.GetAggregates mock is already set by Expect")
	}

	if mmGetAggregates.defaultExpectation.paramPtrs == nil {
		mmGetAggregates.defaultExpectation.paramPtrs = &AggregateServiceMockGetAggregatesParamPtrs{}
	}
	mmGetAggregates.defaultExpectation.paramPtrs.name = &name
	mmGetAggregates.defaultExpectation.expectationOrigins.originName = minimock.CallerInfo(1)

	return mmGetAggregates
}

// Inspect accepts an inspector function that has same arguments as the AggregateService.GetAggregates
func (mmGetAggregates *mAggregateServiceMockGetAggregates) Inspect(f func(ctx context.Context, name string)) *mAggregateServiceMockGetAggregates {
	if mmGetAggregates.mock.inspectFuncGetAggregates != nil {
		mmGetAggregates.mock.t.Fatalf("Inspect function is already set for AggregateServiceMock.GetAggregates")
	}

	mmGetAggregates.mock.inspectFuncGetAggregates = f

	return mmGetAggregates
}

// Return sets up results that will be returned by AggregateService.GetAggregates
func (mmGetAggregates *mAggregateServiceMockGetAggregates) Return(aa1 []entities.Aggregate, err error) *AggregateServiceMock {
	if mmGetAggregates.mock.funcGetAggregates != nil {
		mmGetAggregates.mock.t.Fatalf("AggregateServiceMock.GetAggregates mock is already set by Set")
	}

	if mmGetAggregates.defaultExpectation == nil {
		mmGetAggregates.defaultExpectation = &AggregateServiceMockGetAggregatesExpectation{mock: mmGetAggregates.mock}
	}
	mmGetAggregates.defaultExpectation.results = &AggregateServiceMockGetAggregatesResults{aa1, err}
	mmGetAggregates.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmGetAggregates.mock
}

// Set uses given function f to mock the AggregateService.GetAggregates method
func (mmGetAggregates *mAggregateServiceMockGetAggregates) Set(f func(ctx context.Context, name string) (aa1 []entities.Aggregate, err error)) *AggregateServiceMock {
	if mmGetAggregates.defaultExpectation != nil {
		mmGetAggregates.mock.t.Fatalf("Default expectation is already set for the AggregateService.GetAggregates method")
	}

	if len(mmGetAggregates.expectations) > 0 {
		mmGetAggregates.mock.t.Fatalf("Some expectations are already set for the AggregateService.GetAggregates method")
	}

	mmGetAggregates.mock.funcGetAggregates = f
	mmGetAggregates.mock.funcGetAggregatesOrigin = minimock.CallerInfo(1)
	return mmGetAggregates.mock
}

// When sets expectation for the AggregateService.GetAggregates which will trigger the result defined by the following
// Then helper
func (mmGetAggregates *mAggregateServiceMockGetAggregates) When(ctx context.Context, name string) *AggregateServiceMockGetAggregatesExpectation {
	if mmGetAggregates.mock.funcGetAggregates != nil {
		mmGetAggregates.mock.t.Fatalf("AggregateServiceMock.GetAggregates mock is already set by Set")
	}

	expectation := &AggregateServiceMockGetAggregatesExpectation{
		mock:               mmGetAggregates.mock,
		params:             &AggregateServiceMockGetAggregatesParams{ctx, name},
		expectationOrigins: AggregateServiceMockGetAggregatesExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmGetAggregates.expectations = append(mmGetAggregates.expectations, expectation)
	return expectation
}

// Then sets up AggregateService.GetAggregates return parameters for the expectation previously defined by the When method
func (e *AggregateServiceMockGetAggregatesExpectation) Then(aa1 []entities.Aggregate, err error) *AggregateServiceMock {
	e.results = &AggregateServiceMockGetAggregatesResults{aa1, err}
	return e.mock
}

// Times sets number of times AggregateService.GetAggregates should be invoked
func (mmGetAggregates *mAggregateServiceMockGetAggregates) Times(n uint64) *mAggregateServiceMockGetAggregates {
	if n == 0 {
		mmGetAggregates.mock.t.Fatalf("Times of AggregateServiceMock.GetAggregates mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmGetAggregates.expectedInvocations, n)
	mmGetAggregates.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmGetAggregates
}

func (mmGetAggregates *mAggregateServiceMockGetAggregates) invocationsDone() bool {
	if len(mmGetAggregates.expectations) == 0 && mmGetAggregates.defaultExpectation == nil && mmGetAggregates.mock.funcGetAggregates == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmGetAggregates.mock.afterGetAggregatesCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmGetAggregates.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// GetAggregates implements mm_usecase.AggregateService
func (mmGetAggregates *AggregateServiceMock) GetAggregates(ctx context.Context, name string) (aa1 []entities.Aggregate, err error) {
	mm_atomic.AddUint64(&mmGetAggregates.beforeGetAggregatesCounter, 1)
	defer mm_atomic.AddUint64(&mmGetAggregates.afterGetAggregatesCounter, 1)

	mmGetAggregates.t.Helper()

	if mmGetAggregates.inspectFuncGetAggregates != nil {
		mmGetAggregates.inspectFuncGetAggregates(ctx, name)
	}

	mm_params := AggregateServiceMockGetAggregatesParams{ctx, name}

	// Record call args
	mmGetAggregates.GetAggregatesMock.mutex.Lock()
	mmGetAggregates.GetAggregatesMock.callArgs = append(mmGetAggregates.GetAggregatesMock.callArgs, &mm_params)
	mmGetAggregates.GetAggregatesMock.mutex.Unlock()

	for _, e := range mmGetAggregates.GetAggregatesMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.aa1, e.results.err
		}
	}

	if mmGetAggregates.GetAggregatesMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmGetAggregates.GetAggregatesMock.defaultExpectation.Counter, 1)
		mm_want := mmGetAggregates.GetAggregatesMock.defaultExpectation.params
		mm_want_ptrs := mmGetAggregates.GetAggregatesMock.defaultExpectation.paramPtrs

		mm_got := AggregateServiceMockGetAggregatesParams{ctx, name}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmGetAggregates.t.Errorf("AggregateServiceMock.GetAggregates got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmGetAggregates.GetAggregatesMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.name != nil && !minimock.Equal(*mm_want_ptrs.name, mm_got.name) {
				mmGetAggregates.t.Errorf("AggregateServiceMock.GetAggregates got unexpected parameter name, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmGetAggregates.GetAggregatesMock.defaultExpectation.expectationOrigins.originName, *mm_want_ptrs.name, mm_got.name, minimock.Diff(*mm_want_ptrs.name, mm_got.name))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmGetAggregates.t.Errorf("AggregateServiceMock.GetAggregates got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmGetAggregates.GetAggregatesMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmGetAggregates.GetAggregatesMock.defaultExpectation.results
		if mm_results == nil {
			mmGetAggregates.t.Fatal("No results are set for the AggregateServiceMock.GetAggregates")
		}
		return (*mm_results).aa1, (*mm_results).err
	}
	if mmGetAggregates.funcGetAggregates != nil {
		return mmGetAggregates.funcGetAggregates(ctx, name)
	}
	mmGetAggregates.t.Fatalf("Unexpected call to AggregateServiceMock.GetAggregates. %v %v", ctx, name)
	return
}

// GetAggregatesAfterCounter returns a count of finished AggregateServiceMock.GetAggregates invocations
func (mmGetAggregates *AggregateServiceMock) GetAggregatesAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGetAggregates.afterGetAggregatesCounter)
}

// GetAggregatesBeforeCounter returns a count of AggregateServiceMock.GetAggregates invocations
func (mmGetAggregates *AggregateServiceMock) GetAggregatesBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGetAggregates.beforeGetAggregatesCounter)
}

// Calls returns a list of arguments used in each call to AggregateServiceMock.GetAggregates.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmGetAggregates *mAggregateServiceMockGetAggregates) Calls() []*AggregateServiceMockGetAggregatesParams {
	mmGetAggregates.mutex.RLock()

	argCopy := make([]*AggregateServiceMockGetAggregatesParams, len(mmGetAggregates.callArgs))
	copy(argCopy, mmGetAggregates.callArgs)

	mmGetAggregates.mutex.RUnlock()

	return argCopy
}

// MinimockGetAggregatesDone returns true if the count of the GetAggregates invocations corresponds
// the number of defined expectations
func (m *AggregateServiceMock) MinimockGetAggregatesDone() bool {
	if m.GetAggregatesMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.GetAggregatesMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.GetAggregatesMock.invocationsDone()
}

// MinimockGetAggregatesInspect logs each unmet expectation
func (m *AggregateServiceMock) MinimockGetAggregatesInspect() {
	for _, e := range m.GetAggregatesMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to AggregateServiceMock.GetAggregates at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterGetAggregatesCounter := mm_atomic.LoadUint64(&m.afterGetAggregatesCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.GetAggregatesMock.defaultExpectation != nil && afterGetAggregatesCounter < 1 {
		if m.GetAggregatesMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to AggregateServiceMock.GetAggregates at\n%s", m.GetAggregatesMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to AggregateServiceMock.GetAggregates at\n%s with params: %#v", m.GetAggregatesMock.defaultExpectation.expectationOrigins.origin, *m.GetAggregatesMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcGetAggregates != nil && afterGetAggregatesCounter < 1 {
		m.t.Errorf("Expected call to AggregateServiceMock.GetAggregates at\n%s", m.funcGetAggregatesOrigin)
	}

	if !m.GetAggregatesMock.invocationsDone() && afterGetAggregatesCounter > 0 {
		m.t.Errorf("Expected %d calls to AggregateServiceMock.GetAggregates at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.GetAggregatesMock.expectedInvocations), m.GetAggregatesMock.expectedInvocationsOrigin, afterGetAggregatesCounter)
	}
}

type mAggregateServiceMockUpdateAggregate struct {
	optional           bool
	mock               *AggregateServiceMock
	defaultExpectation *AggregateServiceMockUpdateAggregateExpectation
	expectations       []*AggregateServiceMockUpdateAggregateExpectation

	callArgs []*AggregateServiceMockUpdateAggregateParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// AggregateServiceMockUpdateAggregateExpectation specifies expectation struct of the AggregateService.UpdateAggregate
type AggregateServiceMockUpdateAggregateExpectation struct {
	mock               *AggregateServiceMock
	params             *AggregateServiceMockUpdateAggregateParams
	paramPtrs          *AggregateServiceMockUpdateAggregateParamPtrs
	expectationOrigins AggregateServiceMockUpdateAggregateExpectationOrigins
	results            *AggregateServiceMockUpdateAggregateResults
	returnOrigin       string
	Counter            uint64
}

// AggregateServiceMockUpdateAggregateParams contains parameters of the AggregateService.UpdateAggregate
type AggregateServiceMockUpdateAggregateParams struct {
	ctx     context.Context
	id      uint
	updates map[string]any
}

// AggregateServiceMockUpdateAggregateParamPtrs contains pointers to parameters of the AggregateService.UpdateAggregate
type AggregateServiceMockUpdateAggregateParamPtrs struct {
	ctx     *context.Context
	id      *uint
	updates *map[string]any
}

// AggregateServiceMockUpdateAggregateResults contains results of the AggregateService.UpdateAggregate
type AggregateServiceMockUpdateAggregateResults struct {
	ap1 *entities.Aggregate
	err error
}

// AggregateServiceMockUpdateAggregateOrigins contains origins of expectations of the AggregateService.UpdateAggregate
type AggregateServiceMockUpdateAggregateExpectationOrigins struct {
	origin        string
	originCtx     string
	originId      string
	originUpdates string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmUpdateAggregate *mAggregateServiceMockUpdateAggregate) Optional() *mAggregateServiceMockUpdateAggregate {
	mmUpdateAggregate.optional = true
	return mmUpdateAggregate
}

// Expect sets up expected params for AggregateService.UpdateAggregate
func (mmUpdateAggregate *mAggregateServiceMockUpdateAggregate) Expect(ctx context.Context, id uint, updates map[string]any) *mAggregateServiceMockUpdateAggregate {
	if mmUpdateAggregate.mock.funcUpdateAggregate != nil {
		mmUpdateAggregate.mock.t.Fatalf("AggregateServiceMock.UpdateAggregate mock is already set by Set")
	}

	if mmUpdateAggregate.defaultExpectation == nil {
		mmUpdateAggregate.defaultExpectation = &AggregateServiceMockUpdateAggregateExpectation{}
	}

	if mmUpdateAggregate.defaultExpectation.paramPtrs != nil {
		mmUpdateAggregate.mock.t.Fatalf("AggregateServiceMock.UpdateAggregate mock is already set by ExpectParams functions")
	}

	mmUpdateAggregate.defaultExpectation.params = &AggregateServiceMockUpdateAggregateParams{ctx, id, updates}
	mmUpdateAggregate.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmUpdateAggregate.expectations {
		if minimock.Equal(e.params, mmUpdateAggregate.defaultExpectation.params) {
			mmUpdateAggregate.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmUpdateAggregate.defaultExpectation.params)
		}
	}

	return mmUpdateAggregate
}

// ExpectCtxParam1 sets up expected param ctx for AggregateService.UpdateAggregate
func (mmUpdateAggregate *mAggregateServiceMockUpdateAggregate) ExpectCtxParam1(ctx context.Context) *mAggregateServiceMockUpdateAggregate {
	if mmUpdateAggregate.mock.funcUpdateAggregate != nil {
		mmUpdateAggregate.mock.t.Fatalf("AggregateServiceMock.UpdateAggregate mock is already set by Set")
	}

	if mmUpdateAggregate.defaultExpectation == nil {
		mmUpdateAggregate.defaultExpectation = &AggregateServiceMockUpdateAggregateExpectation{}
	}

	if mmUpdateAggregate.defaultExpectation.params != nil {
		mmUpdateAggregate.mock.t.Fatalf("AggregateServiceMock.UpdateAggregate mock is already set by Expect")
	}

	if mmUpdateAggregate.defaultExpectation.paramPtrs == nil {
		mmUpdateAggregate.defaultExpectation.paramPtrs = &AggregateServiceMockUpdateAggregateParamPtrs{}
	}
	mmUpdateAggregate.defaultExpectation.paramPtrs.ctx = &ctx
	mmUpdateAggregate.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmUpdateAggregate
}

// ExpectIdParam2 sets up expected param id for AggregateService.UpdateAggregate
func (mmUpdateAggregate *mAggregateServiceMockUpdateAggregate) ExpectIdParam2(id uint) *mAggregateServiceMockUpdateAggregate {
	if mmUpdateAggregate.mock.funcUpdateAggregate != nil {
		mmUpdateAggregate.mock.t.Fatalf("AggregateServiceMock.UpdateAggregate mock is already set by Set")
	}

	if mmUpdateAggregate.defaultExpectation == nil {
		mmUpdateAggregate.defaultExpectation = &AggregateServiceMockUpdateAggregateExpectation{}
	}

	if mmUpdateAggregate.defaultExpectation.params != nil {
		mmUpdateAggregate.mock.t.Fatalf("AggregateServiceMock.UpdateAggregate mock is already set by Expect")
	}

	if mmUpdateAggregate.defaultExpectation.paramPtrs == nil {
		mmUpdateAggregate.defaultExpectation.paramPtrs = &AggregateServiceMockUpdateAggregateParamPtrs{}
	}
	mmUpdateAggregate.defaultExpectation.paramPtrs.id = &id
	mmUpdateAggregate.defaultExpectation.expectationOrigins.originId = minimock.CallerInfo(1)

	return mmUpdateAggregate
}

// ExpectUpdatesParam3 sets up expected param updates for AggregateService.UpdateAggregate
func (mmUpdateAggregate *mAggregateServiceMockUpdateAggregate) ExpectUpdatesParam3(updates map[string]any) *mAggregateServiceMockUpdateAggregate {
	if mmUpdateAggregate.mock.funcUpdateAggregate != nil {
		mmUpdateAggregate.mock.t.Fatalf("AggregateServiceMock.UpdateAggregate mock is already set by Set")
	}

	if mmUpdateAggregate.defaultExpectation == nil {
		mmUpdateAggregate.defaultExpectation = &AggregateServiceMockUpdateAggregateExpectation{}
	}

	if mmUpdateAggregate.defaultExpectation.params != nil {
		mmUpdateAggregate.mock.t.Fatalf("AggregateServiceMock.UpdateAggregate mock is already set by Expect")
	}

	if mmUpdateAggregate.defaultExpectation.paramPtrs == nil {
		mmUpdateAggregate.defaultExpectation.paramPtrs = &AggregateServiceMockUpdateAggregateParamPtrs{}
	}
	mmUpdateAggregate.defaultExpectation.paramPtrs.updates = &updates
	mmUpdateAggregate.defaultExpectation.expectationOrigins.originUpdates = minimock.CallerInfo(1)

	return mmUpdateAggregate
}

// Inspect accepts an inspector function that has same arguments as the AggregateService.UpdateAggregate
func (mmUpdateAggregate *mAggregateServiceMockUpdateAggregate) Inspect(f func(ctx context.Context, id uint, updates map[string]any)) *mAggregateServiceMockUpdateAggregate {
	if mmUpdateAggregate.mock.inspectFuncUpdateAggregate != nil {
		mmUpdateAggregate.mock.t.Fatalf("Inspect function is already set for AggregateServiceMock.UpdateAggregate")
	}

	mmUpdateAggregate.mock.inspectFuncUpdateAggregate = f

	return mmUpdateAggregate
}

// Return sets up results that will be returned by AggregateService.UpdateAggregate
func (mmUpdateAggregate *mAggregateServiceMockUpdateAggregate) Return(ap1 *entities.Aggregate, err error) *AggregateServiceMock {
	if mmUpdateAggregate.mock.funcUpdateAggregate != nil {
		mmUpdateAggregate.mock.t.Fatalf("AggregateServiceMock.UpdateAggregate mock is already set by Set")
	}

	if mmUpdateAggregate.defaultExpectation == nil {
		mmUpdateAggregate.defaultExpectation = &AggregateServiceMockUpdateAggregateExpectation{mock: mmUpdateAggregate.mock}
	}
	mmUpdateAggregate.defaultExpectation.results = &AggregateServiceMockUpdateAggregateResults{ap1, err}
	mmUpdateAggregate.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmUpdateAggregate.mock
}

// Set uses given function f to mock the AggregateService.UpdateAggregate method
func (mmUpdateAggregate *mAggregateServiceMockUpdateAggregate) Set(f func(ctx context.Context, id uint, updates map[string]any) (ap1 *entities.Aggregate, err error)) *AggregateServiceMock {
	if mmUpdateAggregate.defaultExpectation != nil {
		mmUpdateAggregate.mock.t.Fatalf("Default expectation is already set for the AggregateService.UpdateAggregate method")
	}

	if len(mmUpdateAggregate.expectations) > 0 {
		mmUpdateAggregate.mock.t.Fatalf("Some expectations are already set for the AggregateService.UpdateAggregate method")
	}

	mmUpdateAggregate.mock.funcUpdateAggregate = f
	mmUpdateAggregate.mock.funcUpdateAggregateOrigin = minimock.CallerInfo(1)
	return mmUpdateAggregate.mock
}

// When sets expectation for the AggregateService.UpdateAggregate which will trigger the result defined by the following
// Then helper
func (mmUpdateAggregate *mAggregateServiceMockUpdateAggregate) When(ctx context.Context, id uint, updates map[string]any) *AggregateServiceMockUpdateAggregateExpectation {
	if mmUpdateAggregate.mock.funcUpdateAggregate != nil {
		mmUpdateAggregate.mock.t.Fatalf("AggregateServiceMock.UpdateAggregate mock is already set by Set")
	}

	expectation := &AggregateServiceMockUpdateAggregateExpectation{
		mock:               mmUpdateAggregate.mock,
		params:             &AggregateServiceMockUpdateAggregateParams{ctx, id, updates},
		expectationOrigins: AggregateServiceMockUpdateAggregateExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmUpdateAggregate.expectations = append(mmUpdateAggregate.expectations, expectation)
	return expectation
}

// Then sets up AggregateService.UpdateAggregate return parameters for the expectation previously defined by the When method
func (e *AggregateServiceMockUpdateAggregateExpectation) Then(ap1 *entities.Aggregate, err error) *AggregateServiceMock {
	e.results = &AggregateServiceMockUpdateAggregateResults{ap1, err}
	return e.mock
}

// Times sets number of times AggregateService.UpdateAggregate should be invoked
func (mmUpdateAggregate *mAggregateServiceMockUpdateAggregate) Times(n uint64) *mAggregateServiceMockUpdateAggregate {
	if n == 0 {
		mmUpdateAggregate.mock.t.Fatalf("Times of AggregateServiceMock.UpdateAggregate mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmUpdateAggregate.expectedInvocations, n)
	mmUpdateAggregate.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmUpdateAggregate
}

func (mmUpdateAggregate *mAggregateServiceMockUpdateAggregate) invocationsDone() bool {
	if len(mmUpdateAggregate.expectations) == 0 && mmUpdateAggregate.defaultExpectation == nil && mmUpdateAggregate.mock.funcUpdateAggregate == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmUpdateAggregate.mock.afterUpdateAggregateCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmUpdateAggregate.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// UpdateAggregate implements mm_usecase.AggregateService
func (mmUpdateAggregate *AggregateServiceMock) UpdateAggregate(ctx context.Context, id uint, updates map[string]any) (ap1 *entities.Aggregate, err error) {
	mm_atomic.AddUint64(&mmUpdateAggregate.beforeUpdateAggregateCounter, 1)
	defer mm_atomic.AddUint64(&mmUpdateAggregate.afterUpdateAggregateCounter, 1)

	mmUpdateAggregate.t.Helper()

	if mmUpdateAggregate.inspectFuncUpdateAggregate != nil {
		mmUpdateAggregate.inspectFuncUpdateAggregate(ctx, id, updates)
	}

	mm_params := AggregateServiceMockUpdateAggregateParams{ctx, id, updates}

	// Record call args
	mmUpdateAggregate.UpdateAggregateMock.mutex.Lock()
	mmUpdateAggregate.UpdateAggregateMock.callArgs = append(mmUpdateAggregate.UpdateAggregateMock.callArgs, &mm_params)
	mmUpdateAggregate.UpdateAggregateMock.mutex.Unlock()

	for _, e := range mmUpdateAggregate.UpdateAggregateMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.ap1, e.results.err
		}
	}

	if mmUpdateAggregate.UpdateAggregateMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmUpdateAggregate.UpdateAggregateMock.defaultExpectation.Counter, 1)
		mm_want := mmUpdateAggregate.UpdateAggregateMock.defaultExpectation.params
		mm_want_ptrs := mmUpdateAggregate.UpdateAggregateMock.defaultExpectation.paramPtrs

		mm_got := AggregateServiceMockUpdateAggregateParams{ctx, id, updates}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmUpdateAggregate.t.Errorf("AggregateServiceMock.UpdateAggregate got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmUpdateAggregate.UpdateAggregateMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.id != nil && !minimock.Equal(*mm_want_ptrs.id, mm_got.id) {
				mmUpdateAggregate.t.Errorf("AggregateServiceMock.UpdateAggregate got unexpected parameter id, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmUpdateAggregate.UpdateAggregateMock.defaultExpectation.expectationOrigins.originId, *mm_want_ptrs.id, mm_got.id, minimock.Diff(*mm_want_ptrs.id, mm_got.id))
			}

			if mm_want_ptrs.updates != nil && !minimock.Equal(*mm_want_ptrs.updates, mm_got.updates) {
				mmUpdateAggregate.t.Errorf("AggregateServiceMock.UpdateAggregate got unexpected parameter updates, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmUpdateAggregate.UpdateAggregateMock.defaultExpectation.expectationOrigins.originUpdates, *mm_want_ptrs.updates, mm_got.updates, minimock.Diff(*mm_want_ptrs.updates, mm_got.updates))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmUpdateAggregate.t.Errorf("AggregateServiceMock.UpdateAggregate got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmUpdateAggregate.UpdateAggregateMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmUpdateAggregate.UpdateAggregateMock.defaultExpectation.results
		if mm_results == nil {
			mmUpdateAggregate.t.Fatal("No results are set for the AggregateServiceMock.UpdateAggregate")
		}
		return (*mm_results).ap1, (*mm_results).err
	}
	if mmUpdateAggregate.funcUpdateAggregate != nil {
		return mmUpdateAggregate.funcUpdateAggregate(ctx, id, updates)
	}
	mmUpdateAggregate.t.Fatalf("Unexpected call to AggregateServiceMock.UpdateAggregate. %v %v %v", ctx, id, updates)
	return
}

// UpdateAggregateAfterCounter returns a count of finished AggregateServiceMock.UpdateAggregate invocations
func (mmUpdateAggregate *AggregateServiceMock) UpdateAggregateAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmUpdateAggregate.afterUpdateAggregateCounter)
}

// UpdateAggregateBeforeCounter returns a count of AggregateServiceMock.UpdateAggregate invocations
func (mmUpdateAggregate *AggregateServiceMock) UpdateAggregateBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmUpdateAggregate.beforeUpdateAggregateCounter)
}

// Calls returns a list of arguments used in each call to AggregateServiceMock.UpdateAggregate.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmUpdateAggregate *mAggregateServiceMockUpdateAggregate) Calls() []*AggregateServiceMockUpdateAggregateParams {
	mmUpdateAggregate.mutex.RLock()

	argCopy := make([]*AggregateServiceMockUpdateAggregateParams, len(mmUpdateAggregate.callArgs))
	copy(argCopy, mmUpdateAggregate.callArgs)

	mmUpdateAggregate.mutex.RUnlock()

	return argCopy
}

// MinimockUpdateAggregateDone returns true if the count of the UpdateAggregate invocations corresponds
// the number of defined expectations
func (m *AggregateServiceMock) MinimockUpdateAggregateDone() bool {
	if m.UpdateAggregateMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.UpdateAggregateMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.UpdateAggregateMock.invocationsDone()
}

// MinimockUpdateAggregateInspect logs each unmet expectation
func (m *AggregateServiceMock) MinimockUpdateAggregateInspect() {
	for _, e := range m.UpdateAggregateMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to AggregateServiceMock.UpdateAggregate at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterUpdateAggregateCounter := mm_atomic.LoadUint64(&m.afterUpdateAggregateCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.UpdateAggregateMock.defaultExpectation != nil && afterUpdateAggregateCounter < 1 {
		if m.UpdateAggregateMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to AggregateServiceMock.UpdateAggregate at\n%s", m.UpdateAggregateMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to AggregateServiceMock.UpdateAggregate at\n%s with params: %#v", m.UpdateAggregateMock.defaultExpectation.expectationOrigins.origin, *m.UpdateAggregateMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcUpdateAggregate != nil && afterUpdateAggregateCounter < 1 {
		m.t.Errorf("Expected call to AggregateServiceMock.UpdateAggregate at\n%s", m.funcUpdateAggregateOrigin)
	}

	if !m.UpdateAggregateMock.invocationsDone() && afterUpdateAggregateCounter > 0 {
		m.t.Errorf("Expected %d calls to AggregateServiceMock.UpdateAggregate at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.UpdateAggregateMock.expectedInvocations), m.UpdateAggregateMock.expectedInvocationsOrigin, afterUpdateAggregateCounter)
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *AggregateServiceMock) MinimockFinish() {
	m.finishOnce.Do(func() {
		if !m.minimockDone() {
			m.MinimockApplyAggregateToCategoryInspect()

			m.MinimockCreateAggregateInspect()

			m.MinimockDeleteAggregateInspect()

			m.MinimockGetAggregatesInspect()

			m.MinimockUpdateAggregateInspect()
		}
	})
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *AggregateServiceMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *AggregateServiceMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockApplyAggregateToCategoryDone() &&
		m.MinimockCreateAggregateDone() &&
		m.MinimockDeleteAggregateDone() &&
		m.MinimockGetAggregatesDone() &&
		m.MinimockUpdateAggregateDone()
}
